import type { TopicId } from '@retro/types'
import type { NonEmptyArray } from '@retro/room-kit'

/**
 * 초성 퀴즈 문제 풀.
 *
 * **지금은 이 파일이 곧 DB다.** TypeScript 상수라 Worker 번들에 그대로 들어간다.
 * 정식 파이프라인(04 문서)에서는 여기 대신 Workers KV 를 읽고, 방 생성 시
 * 한 번 받아 DO 메모리에 들고 있는다 (05 문서 §5). `ContentPool` 이 그 자리다 —
 * 풀이 비어 있을 때만 아래 상수로 떨어진다.
 *
 * `topic` 은 시대와 직교한다. 「90년대 IT」도 「세계사」도 같은 구조에 들어간다.
 */

export interface ChosungWord {
  readonly word: string
  readonly topic: TopicId
  readonly category: string
  /** 8초에 공개되는 설명 한 줄 */
  readonly hint: string
  /** 사전에 등록된 다른 정답. 복수 정답 허용 — 02 문서 §2.3 */
  readonly aliases: readonly string[]
}

export const SAMPLE_WORDS: NonEmptyArray<ChosungWord> = [
  { word: '삐삐', topic: 'daily', category: '그때 그 물건', hint: '허리에 차고 다녔다', aliases: ['무선호출기'] },
  { word: '워크맨', topic: 'daily', category: '그때 그 물건', hint: '테이프를 넣고 들었다', aliases: [] },
  { word: '다마고치', topic: 'daily', category: '그때 그 물건', hint: '밥 안 주면 죽었다', aliases: [] },
  { word: '브로마이드', topic: 'daily', category: '그때 그 물건', hint: '벽에 붙이던 대형 사진', aliases: [] },
  { word: '시티폰', topic: 'daily', category: '그때 그 물건', hint: '발신만 되던 전화', aliases: [] },
  { word: '공중전화', topic: 'daily', category: '그때 그 물건', hint: '카드나 동전을 넣었다', aliases: [] },
  { word: '카세트테이프', topic: 'daily', category: '그때 그 물건', hint: '연필로 감았다', aliases: ['카세트'] },
  { word: '플로피디스켓', topic: 'daily', category: '그때 그 물건', hint: '1.44MB 였다', aliases: ['디스켓'] },
  { word: '전화카드', topic: 'daily', category: '그때 그 물건', hint: '공중전화에 꽂아 썼다', aliases: [] },
  { word: '버스토큰', topic: 'daily', category: '그때 그 물건', hint: '버스 탈 때 통에 넣었다', aliases: [] },
  { word: '필름카메라', topic: 'daily', category: '그때 그 물건', hint: '현상소에 맡겨야 볼 수 있었다', aliases: [] },
  { word: '시디플레이어', topic: 'daily', category: '그때 그 물건', hint: '원반을 넣어 돌렸다', aliases: ['CD플레이어'] },
  { word: '엠피삼', topic: 'daily', category: '그때 그 물건', hint: '노래를 넣어 다녔다', aliases: ['MP3', '엠피쓰리'] },
  { word: '연탄', topic: 'daily', category: '그때 그 물건', hint: '아궁이에 넣고 갈았다', aliases: [] },
  { word: '곤로', topic: 'daily', category: '그때 그 물건', hint: '석유를 넣어 불을 켰다', aliases: [] },
  { word: '책받침', topic: 'daily', category: '그때 그 물건', hint: '연예인 사진이 들어 있었다', aliases: [] },
  { word: '샤프', topic: 'daily', category: '그때 그 물건', hint: '심을 넣어 쓰는 필기구', aliases: [] },
  { word: '색종이', topic: 'daily', category: '그때 그 물건', hint: '접어서 학을 만들었다', aliases: [] },
  { word: '브이에이치에스', topic: 'daily', category: '그때 그 물건', hint: '네모난 비디오 테이프', aliases: ['VHS', '비디오테이프'] },
  { word: '턴테이블', topic: 'daily', category: '그때 그 물건', hint: '바늘을 올려 판을 돌렸다', aliases: [] },
  { word: '전축', topic: 'daily', category: '그때 그 물건', hint: '거실 한가운데 있었다', aliases: [] },
  { word: '선풍기', topic: 'daily', category: '그때 그 물건', hint: '여름에 목을 돌렸다', aliases: [] },
  { word: '다이얼전화', topic: 'daily', category: '그때 그 물건', hint: '손가락을 넣어 돌렸다', aliases: [] },
  { word: '타자기', topic: 'daily', category: '그때 그 물건', hint: '종이를 끼우고 두드렸다', aliases: [] },
  { word: '보온도시락', topic: 'daily', category: '그때 그 물건', hint: '겨울에 따뜻했다', aliases: [] },
  { word: '양은도시락', topic: 'daily', category: '그때 그 물건', hint: '난로 위에 올려 뒀다', aliases: [] },
  { word: '실내화', topic: 'daily', category: '그때 그 물건', hint: '학교에서 갈아 신었다', aliases: [] },
  { word: '성적표', topic: 'daily', category: '그때 그 물건', hint: '봉투에 담겨 왔다', aliases: [] },
  { word: '문방구', topic: 'daily', category: '그때 그 장소', hint: '학교 앞에 꼭 있었다', aliases: [] },
  { word: '오락실', topic: 'daily', category: '그때 그 장소', hint: '동전을 쌓아두고 줄을 섰다', aliases: [] },
  { word: '만화방', topic: 'daily', category: '그때 그 장소', hint: '라면도 팔았다', aliases: ['만화가게'] },
  { word: '비디오가게', topic: 'daily', category: '그때 그 장소', hint: '연체료가 무서웠다', aliases: ['비디오대여점'] },
  { word: '롤라장', topic: 'daily', category: '그때 그 장소', hint: '바퀴 달린 신발을 빌렸다', aliases: ['롤러장'] },
  { word: '피시방', topic: 'daily', category: '그때 그 장소', hint: '시간당 천 원이었다', aliases: ['PC방'] },
  { word: '노래방', topic: 'daily', category: '그때 그 장소', hint: '한 곡에 얼마씩 받았다', aliases: [] },
  { word: '구멍가게', topic: 'daily', category: '그때 그 장소', hint: '동네 골목에 있었다', aliases: [] },
  { word: '학교매점', topic: 'daily', category: '그때 그 장소', hint: '종 치면 뛰어갔다', aliases: [] },
  { word: '공중목욕탕', topic: 'daily', category: '그때 그 장소', hint: '때를 밀어주는 사람이 있었다', aliases: ['목욕탕'] },
  { word: '레코드가게', topic: 'daily', category: '그때 그 장소', hint: '앨범을 사러 갔다', aliases: [] },
  { word: '사진관', topic: 'daily', category: '그때 그 장소', hint: '증명사진을 찍었다', aliases: [] },
  { word: '컴퓨터학원', topic: 'daily', category: '그때 그 장소', hint: '워드프로세서 자격증을 땄다', aliases: [] },
  { word: '독서실', topic: 'daily', category: '그때 그 장소', hint: '칸막이 책상이 있었다', aliases: [] },
  { word: '다방', topic: 'daily', category: '그때 그 장소', hint: '계란 노른자를 띄워 줬다', aliases: [] },
  { word: '분식집', topic: 'daily', category: '그때 그 장소', hint: '떡볶이와 순대를 팔았다', aliases: [] },
  { word: '놀이터', topic: 'daily', category: '그때 그 장소', hint: '모래밭에 미끄럼틀이 있었다', aliases: [] },
  { word: '죠스바', topic: 'daily', category: '그때 그 군것질', hint: '혀가 파래졌다', aliases: [] },
  { word: '쌍쌍바', topic: 'daily', category: '그때 그 군것질', hint: '반으로 쪼개 나눠 먹었다', aliases: [] },
  { word: '뽀빠이', topic: 'daily', category: '그때 그 군것질', hint: '별사탕이 들어 있었다', aliases: [] },
  { word: '새우깡', topic: 'daily', category: '그때 그 군것질', hint: '손이 가요 손이 가', aliases: [] },
  { word: '빠삐코', topic: 'daily', category: '그때 그 군것질', hint: '튜브를 짜서 먹었다', aliases: [] },
  { word: '메로나', topic: 'daily', category: '그때 그 군것질', hint: '연두색 아이스크림', aliases: [] },
  { word: '바밤바', topic: 'daily', category: '그때 그 군것질', hint: '밤 맛이 났다', aliases: [] },
  { word: '누가바', topic: 'daily', category: '그때 그 군것질', hint: '겉은 초코 속은 아이스크림', aliases: [] },
  { word: '스크류바', topic: 'daily', category: '그때 그 군것질', hint: '꼬여 있는 모양', aliases: [] },
  { word: '밀키스', topic: 'daily', category: '그때 그 군것질', hint: '우유가 들어간 탄산', aliases: [] },
  { word: '맥콜', topic: 'daily', category: '그때 그 군것질', hint: '보리로 만든 탄산', aliases: [] },
  { word: '쿠쿠다스', topic: 'daily', category: '그때 그 군것질', hint: '부서지기 쉬웠다', aliases: [] },
  { word: '초코파이', topic: 'daily', category: '그때 그 군것질', hint: '정을 나눴다', aliases: [] },
  { word: '건빵', topic: 'daily', category: '그때 그 군것질', hint: '별사탕이 같이 들었다', aliases: [] },
  { word: '아폴로', topic: 'daily', category: '그때 그 군것질', hint: '빨대 모양 사탕', aliases: [] },
  { word: '쫀드기', topic: 'daily', category: '그때 그 군것질', hint: '불에 구워 먹었다', aliases: [] },
  { word: '달고나', topic: 'daily', category: '그때 그 군것질', hint: '국자에 설탕을 녹였다', aliases: ['뽑기'] },
  { word: '번데기', topic: 'daily', category: '그때 그 군것질', hint: '종이컵에 담아 팔았다', aliases: [] },
  { word: '솜사탕', topic: 'daily', category: '그때 그 군것질', hint: '막대에 감아 줬다', aliases: [] },
  { word: '호빵', topic: 'daily', category: '그때 그 군것질', hint: '겨울에 김이 났다', aliases: [] },
  { word: '딱지치기', topic: 'daily', category: '그때 그 놀이', hint: '땅에 쳐서 뒤집었다', aliases: ['딱지'] },
  { word: '구슬치기', topic: 'daily', category: '그때 그 놀이', hint: '유리알로 하는 놀이', aliases: [] },
  { word: '고무줄놀이', topic: 'daily', category: '그때 그 놀이', hint: '다리에 걸고 넘었다', aliases: [] },
  { word: '공기놀이', topic: 'daily', category: '그때 그 놀이', hint: '다섯 알을 던져 받았다', aliases: ['공기'] },
  { word: '숨바꼭질', topic: 'daily', category: '그때 그 놀이', hint: '술래가 눈을 감고 셌다', aliases: [] },
  { word: '오징어게임', topic: 'daily', category: '그때 그 놀이', hint: '땅에 그림을 그리고 했다', aliases: [] },
  { word: '제기차기', topic: 'daily', category: '그때 그 놀이', hint: '발등으로 찼다', aliases: [] },
  { word: '팽이치기', topic: 'daily', category: '그때 그 놀이', hint: '줄을 감아 던졌다', aliases: [] },
  { word: '무궁화꽃', topic: 'daily', category: '그때 그 놀이', hint: '뒤돌아보면 멈춰야 했다', aliases: [] },
  { word: '야타족', topic: 'daily', category: '그때 그 유행', hint: '차에 타라고 불렀다', aliases: [] },
  { word: '오빠믿지', topic: 'daily', category: '그때 그 유행', hint: '믿으면 안 됐다', aliases: [] },
  { word: '무스탕', topic: 'daily', category: '그때 그 유행', hint: '겨울에 유행한 외투', aliases: [] },
  { word: '힙합바지', topic: 'daily', category: '그때 그 유행', hint: '통이 아주 넓었다', aliases: [] },
  { word: '떡볶이코트', topic: 'daily', category: '그때 그 유행', hint: '단추가 나무였다', aliases: [] },
  { word: '컬러링', topic: 'daily', category: '그때 그 유행', hint: '전화를 걸면 노래가 나왔다', aliases: [] },
  { word: '폴더폰', topic: 'daily', category: '그때 그 유행', hint: '접었다 폈다 했다', aliases: [] },
  { word: '배꼽티', topic: 'daily', category: '그때 그 유행', hint: '짧은 상의였다', aliases: [] },
  { word: '통굽구두', topic: 'daily', category: '그때 그 유행', hint: '밑창이 아주 두꺼웠다', aliases: [] },
  { word: '모래시계', topic: 'drama', category: '90년대 드라마', hint: '나 지금 떨고 있니', aliases: [] },
  { word: '여명의눈동자', topic: 'drama', category: '90년대 드라마', hint: '일제강점기를 다뤘다', aliases: [] },
  { word: '사랑이뭐길래', topic: 'drama', category: '90년대 드라마', hint: '대발이가 나왔다', aliases: [] },
  { word: '첫사랑', topic: 'drama', category: '90년대 드라마', hint: '시청률 기록을 세웠다', aliases: [] },
  { word: '마지막승부', topic: 'drama', category: '90년대 드라마', hint: '농구 소재 드라마', aliases: [] },
  { word: '별은내가슴에', topic: 'drama', category: '90년대 드라마', hint: '재벌과 신인의 이야기', aliases: [] },
  { word: '허준', topic: 'drama', category: '90년대 드라마', hint: '의학 사극이었다', aliases: [] },
  { word: '겨울연가', topic: 'drama', category: '2000년대 드라마', hint: '한류의 출발점으로 꼽힌다', aliases: [] },
  { word: '가을동화', topic: 'drama', category: '2000년대 드라마', hint: '계절 시리즈의 첫 작품', aliases: [] },
  { word: '대장금', topic: 'drama', category: '2000년대 드라마', hint: '궁중 요리를 다룬 사극', aliases: [] },
  { word: '풀하우스', topic: 'drama', category: '2000년대 드라마', hint: '계약 결혼 이야기', aliases: [] },
  { word: '내이름은김삼순', topic: 'drama', category: '2000년대 드라마', hint: '제빵사가 주인공이었다', aliases: [] },
  { word: '주몽', topic: 'drama', category: '2000년대 드라마', hint: '고구려 건국 사극', aliases: [] },
  { word: '시크릿가든', topic: 'drama', category: '2000년대 드라마', hint: '몸이 바뀌는 이야기', aliases: [] },
  { word: '전원일기', topic: 'drama', category: '가족·시트콤', hint: '20년 넘게 방영된 농촌 드라마', aliases: [] },
  { word: '순풍산부인과', topic: 'drama', category: '가족·시트콤', hint: '미달이가 나왔다', aliases: ['순풍'] },
  { word: '세친구', topic: 'drama', category: '가족·시트콤', hint: '성인 시트콤이었다', aliases: [] },
  { word: '논스톱', topic: 'drama', category: '가족·시트콤', hint: '대학 시트콤 시리즈', aliases: [] },
  { word: '하이킥', topic: 'drama', category: '가족·시트콤', hint: '가족 시트콤 시리즈', aliases: ['거침없이하이킥'] },
  { word: '남자셋여자셋', topic: 'drama', category: '가족·시트콤', hint: '대학생 시트콤', aliases: [] },
  { word: '쉬리', topic: 'movie', category: '한국 영화', hint: '한국 영화 흥행 기록을 새로 썼다', aliases: [] },
  { word: '접속', topic: 'movie', category: '한국 영화', hint: 'PC통신으로 만나는 이야기', aliases: [] },
  { word: '엽기적인그녀', topic: 'movie', category: '한국 영화', hint: '지하철에서 시작됐다', aliases: [] },
  { word: '친구', topic: 'movie', category: '한국 영화', hint: '부산 사투리가 화제였다', aliases: [] },
  { word: '공동경비구역', topic: 'movie', category: '한국 영화', hint: '판문점을 배경으로 했다', aliases: ['JSA'] },
  { word: '올드보이', topic: 'movie', category: '한국 영화', hint: '칸 영화제에서 상을 받았다', aliases: [] },
  { word: '살인의추억', topic: 'movie', category: '한국 영화', hint: '미제 사건을 다뤘다', aliases: [] },
  { word: '실미도', topic: 'movie', category: '한국 영화', hint: '천만 관객을 처음 넘겼다', aliases: [] },
  { word: '태극기휘날리며', topic: 'movie', category: '한국 영화', hint: '한국전쟁 형제 이야기', aliases: [] },
  { word: '왕의남자', topic: 'movie', category: '한국 영화', hint: '광대 이야기', aliases: [] },
  { word: '괴물', topic: 'movie', category: '한국 영화', hint: '한강에 괴물이 나타난다', aliases: [] },
  { word: '기생충', topic: 'movie', category: '한국 영화', hint: '아카데미 작품상을 받았다', aliases: [] },
  { word: '부산행', topic: 'movie', category: '한국 영화', hint: '기차 안에서 벌어진다', aliases: [] },
  { word: '명량', topic: 'movie', category: '한국 영화', hint: '열두 척으로 싸운 해전', aliases: [] },
  { word: '국제시장', topic: 'movie', category: '한국 영화', hint: '부산을 배경으로 한 가족사', aliases: [] },
  { word: '베테랑', topic: 'movie', category: '한국 영화', hint: '형사가 재벌을 쫓는다', aliases: [] },
  { word: '건축학개론', topic: 'movie', category: '한국 영화', hint: '첫사랑을 다뤘다', aliases: [] },
  { word: '타이타닉', topic: 'movie', category: '해외 영화', hint: '배가 침몰하는 이야기', aliases: [] },
  { word: '터미네이터', topic: 'movie', category: '해외 영화', hint: '기계와 싸운다', aliases: [] },
  { word: '쥬라기공원', topic: 'movie', category: '해외 영화', hint: '공룡이 되살아났다', aliases: [] },
  { word: '매트릭스', topic: 'movie', category: '해외 영화', hint: '빨간 약과 파란 약', aliases: [] },
  { word: '반지의제왕', topic: 'movie', category: '해외 영화', hint: '반지를 버리러 간다', aliases: [] },
  { word: '해리포터', topic: 'movie', category: '해외 영화', hint: '마법 학교 이야기', aliases: [] },
  { word: '스타워즈', topic: 'movie', category: '해외 영화', hint: '포스가 함께하기를', aliases: [] },
  { word: '아바타', topic: 'movie', category: '해외 영화', hint: '파란 외계인이 나온다', aliases: [] },
  { word: '인터스텔라', topic: 'movie', category: '해외 영화', hint: '블랙홀을 지나간다', aliases: [] },
  { word: '포레스트검프', topic: 'movie', category: '해외 영화', hint: '계속 달린다', aliases: [] },
  { word: '쇼생크탈출', topic: 'movie', category: '해외 영화', hint: '감옥에서 탈출한다', aliases: [] },
  { word: '아기공룡둘리', topic: 'anime', category: '한국 만화·애니', hint: '빙하를 타고 왔다', aliases: ['둘리'] },
  { word: '영심이', topic: 'anime', category: '한국 만화·애니', hint: '사춘기 소녀 이야기', aliases: [] },
  { word: '달려라하니', topic: 'anime', category: '한국 만화·애니', hint: '육상 선수 소녀', aliases: [] },
  { word: '검정고무신', topic: 'anime', category: '한국 만화·애니', hint: '형제 이야기', aliases: [] },
  { word: '로보트태권브이', topic: 'anime', category: '한국 만화·애니', hint: '태권도를 하는 로봇', aliases: ['태권브이'] },
  { word: '슬램덩크', topic: 'anime', category: '일본 만화·애니', hint: '왼손은 거들 뿐', aliases: [] },
  { word: '드래곤볼', topic: 'anime', category: '일본 만화·애니', hint: '구슬을 모으면 소원이 이뤄진다', aliases: [] },
  { word: '세일러문', topic: 'anime', category: '일본 만화·애니', hint: '달을 대신해 벌한다', aliases: [] },
  { word: '원피스', topic: 'anime', category: '일본 만화·애니', hint: '해적왕을 꿈꾼다', aliases: [] },
  { word: '나루토', topic: 'anime', category: '일본 만화·애니', hint: '닌자가 주인공이다', aliases: [] },
  { word: '명탐정코난', topic: 'anime', category: '일본 만화·애니', hint: '몸이 작아진 탐정', aliases: [] },
  { word: '짱구는못말려', topic: 'anime', category: '일본 만화·애니', hint: '다섯 살 개구쟁이', aliases: ['짱구'] },
  { word: '도라에몽', topic: 'anime', category: '일본 만화·애니', hint: '주머니에서 도구가 나온다', aliases: [] },
  { word: '건담', topic: 'anime', category: '일본 만화·애니', hint: '거대 로봇이 나온다', aliases: [] },
  { word: '토토로', topic: 'anime', category: '일본 만화·애니', hint: '숲에 사는 존재', aliases: [] },
  { word: '센과치히로', topic: 'anime', category: '일본 만화·애니', hint: '이름을 빼앗기는 이야기', aliases: [] },
  { word: '하울의움직이는성', topic: 'anime', category: '일본 만화·애니', hint: '걸어 다니는 성', aliases: [] },
  { word: '서태지와아이들', topic: 'music', category: '90년대 가요', hint: '「난 알아요」 로 데뷔했다', aliases: ['서태지'] },
  { word: '김건모', topic: 'music', category: '90년대 가요', hint: '「잘못된 만남」 을 불렀다', aliases: [] },
  { word: '룰라', topic: 'music', category: '90년대 가요', hint: '「날개 잃은 천사」', aliases: [] },
  { word: '클론', topic: 'music', category: '90년대 가요', hint: '「꿍따리 샤바라」', aliases: [] },
  { word: '디제이덕', topic: 'music', category: '90년대 가요', hint: '「머리 어깨 무릎 발」', aliases: ['DJ DOC'] },
  { word: '이문세', topic: 'music', category: '90년대 가요', hint: '「붉은 노을」 을 불렀다', aliases: [] },
  { word: '신승훈', topic: 'music', category: '90년대 가요', hint: '발라드의 황제로 불렸다', aliases: [] },
  { word: '조성모', topic: 'music', category: '90년대 가요', hint: '뮤직비디오가 영화 같았다', aliases: [] },
  { word: '김광석', topic: 'music', category: '90년대 가요', hint: '「서른 즈음에」 를 불렀다', aliases: [] },
  { word: '신해철', topic: 'music', category: '90년대 가요', hint: '넥스트를 이끌었다', aliases: [] },
  { word: '에이치오티', topic: 'music', category: '아이돌', hint: '흰 풍선을 흔들었다', aliases: ['HOT', 'H.O.T'] },
  { word: '젝스키스', topic: 'music', category: '아이돌', hint: '노란 풍선이었다', aliases: ['젝키'] },
  { word: '핑클', topic: 'music', category: '아이돌', hint: '4인조 여성 그룹', aliases: [] },
  { word: '에스이에스', topic: 'music', category: '아이돌', hint: '3인조 여성 그룹이었다', aliases: ['SES', 'S.E.S'] },
  { word: '신화', topic: 'music', category: '아이돌', hint: '장수 아이돌 그룹', aliases: [] },
  { word: '지오디', topic: 'music', category: '아이돌', hint: '「어머님께」 를 불렀다', aliases: ['god'] },
  { word: '보아', topic: 'music', category: '아이돌', hint: '일본에서도 1위를 했다', aliases: [] },
  { word: '동방신기', topic: 'music', category: '아이돌', hint: '5인조로 데뷔했다', aliases: [] },
  { word: '빅뱅', topic: 'music', category: '아이돌', hint: '「거짓말」 이 크게 인기였다', aliases: [] },
  { word: '소녀시대', topic: 'music', category: '아이돌', hint: '9인조 여성 그룹', aliases: [] },
  { word: '원더걸스', topic: 'music', category: '아이돌', hint: '「텔미」 가 유행했다', aliases: [] },
  { word: '슈퍼주니어', topic: 'music', category: '아이돌', hint: '대규모 남성 그룹', aliases: [] },
  { word: '투애니원', topic: 'music', category: '아이돌', hint: '「내가 제일 잘 나가」', aliases: ['2NE1'] },
  { word: '싸이', topic: 'music', category: '아이돌', hint: '「강남스타일」 로 세계적 인기', aliases: [] },
  { word: '방탄소년단', topic: 'music', category: '아이돌', hint: '빌보드 1위를 했다', aliases: ['BTS'] },
  { word: '블랙핑크', topic: 'music', category: '아이돌', hint: '세계적으로 인기다', aliases: [] },
  { word: '가요톱텐', topic: 'music', category: '음악 문화', hint: '5주 연속 1위면 골든컵', aliases: [] },
  { word: '인기가요', topic: 'music', category: '음악 문화', hint: '일요일 음악 순위 프로그램', aliases: [] },
  { word: '뮤직뱅크', topic: 'music', category: '음악 문화', hint: '금요일 음악 프로그램', aliases: [] },
  { word: '테이프', topic: 'music', category: '음악 문화', hint: '늘어지면 연필로 감았다', aliases: [] },
  { word: '시디', topic: 'music', category: '음악 문화', hint: '원반 형태 음반', aliases: ['CD'] },
  { word: '엘피', topic: 'music', category: '음악 문화', hint: '판을 바늘로 읽는다', aliases: ['LP'] },
  { word: '멜론', topic: 'music', category: '음악 문화', hint: '국내 음악 서비스', aliases: [] },
  { word: '워크맨', topic: 'music', category: '음악 문화', hint: '테이프를 넣고 들었다', aliases: [] },
  { word: '무한도전', topic: 'culture', category: '예능·방송', hint: '평균 이하를 표방했다', aliases: [] },
  { word: '일요일일요일밤에', topic: 'culture', category: '예능·방송', hint: '주말 예능의 대표였다', aliases: [] },
  { word: '개그콘서트', topic: 'culture', category: '예능·방송', hint: '공개 코미디 프로그램', aliases: [] },
  { word: '일박이일', topic: 'culture', category: '예능·방송', hint: '여행 예능이다', aliases: ['1박2일'] },
  { word: '런닝맨', topic: 'culture', category: '예능·방송', hint: '이름표를 떼는 게임', aliases: [] },
  { word: '전국노래자랑', topic: 'culture', category: '예능·방송', hint: '딩동댕', aliases: [] },
  { word: '브로마이드', topic: 'culture', category: '예능·방송', hint: '벽에 붙이던 대형 사진', aliases: [] },
  { word: '하이텔', topic: 'it', category: 'PC통신', hint: '전화선으로 접속했다', aliases: [] },
  { word: '천리안', topic: 'it', category: 'PC통신', hint: '3대 PC통신 중 하나', aliases: [] },
  { word: '나우누리', topic: 'it', category: 'PC통신', hint: '동호회가 활발했다', aliases: [] },
  { word: '모뎀', topic: 'it', category: 'PC통신', hint: '접속할 때 소리가 요란했다', aliases: [] },
  { word: '전화접속', topic: 'it', category: 'PC통신', hint: '쓰면 집 전화가 안 됐다', aliases: [] },
  { word: '아이러브스쿨', topic: 'it', category: 'PC통신', hint: '동창을 찾아줬다', aliases: [] },
  { word: '스타크래프트', topic: 'game', category: '그때 그 게임', hint: '저글링 러시', aliases: ['스타'] },
  { word: '바람의나라', topic: 'game', category: '그때 그 게임', hint: '국내 최초 그래픽 머드', aliases: [] },
  { word: '크레이지아케이드', topic: 'game', category: '그때 그 게임', hint: '물풍선을 터뜨렸다', aliases: ['크아'] },
  { word: '테트리스', topic: 'game', category: '그때 그 게임', hint: '한 줄씩 지웠다', aliases: [] },
  { word: '리니지', topic: 'game', category: '그때 그 게임', hint: '혈맹과 공성전', aliases: [] },
  { word: '디아블로', topic: 'game', category: '그때 그 게임', hint: '어두운 던전을 돌았다', aliases: [] },
  { word: '포트리스', topic: 'game', category: '그때 그 게임', hint: '각도와 세기를 맞췄다', aliases: [] },
  { word: '카트라이더', topic: 'game', category: '그때 그 게임', hint: '부스터를 썼다', aliases: [] },
  { word: '메이플스토리', topic: 'game', category: '그때 그 게임', hint: '옆으로 걷는 게임', aliases: [] },
  { word: '던전앤파이터', topic: 'game', category: '그때 그 게임', hint: '때리는 맛이 있었다', aliases: ['던파'] },
  { word: '서든어택', topic: 'game', category: '그때 그 게임', hint: '총으로 싸웠다', aliases: [] },
  { word: '워크래프트', topic: 'game', category: '그때 그 게임', hint: '유즈맵이 유행했다', aliases: [] },
  { word: '페르시아왕자', topic: 'game', category: '그때 그 게임', hint: '시간 안에 탈출했다', aliases: [] },
  { word: '갤러그', topic: 'game', category: '그때 그 게임', hint: '우주선으로 쐈다', aliases: [] },
  { word: '보글보글', topic: 'game', category: '그때 그 게임', hint: '거품으로 잡았다', aliases: [] },
  { word: '스트리트파이터', topic: 'game', category: '그때 그 게임', hint: '승룡권을 썼다', aliases: [] },
  { word: '킹오브파이터즈', topic: 'game', category: '그때 그 게임', hint: '3대3으로 싸웠다', aliases: ['KOF'] },
  { word: '삼국지', topic: 'game', category: '그때 그 게임', hint: '제갈량이 나오는 전략 게임', aliases: [] },
  { word: '싸이월드', topic: 'it', category: '인터넷 서비스', hint: '도토리로 배경음악을 샀다', aliases: ['싸이'] },
  { word: '미니홈피', topic: 'it', category: '인터넷 서비스', hint: '일촌만 볼 수 있었다', aliases: [] },
  { word: '엠에스엔', topic: 'it', category: '인터넷 서비스', hint: '메신저로 대화했다', aliases: ['MSN'] },
  { word: '도토리', topic: 'it', category: '인터넷 서비스', hint: '아이템을 사는 화폐였다', aliases: [] },
  { word: '디시인사이드', topic: 'it', category: '인터넷 서비스', hint: '갤러리로 나뉘어 있다', aliases: ['디시'] },
  { word: '네이버지식인', topic: 'it', category: '인터넷 서비스', hint: '묻고 답했다', aliases: ['지식인'] },
  { word: '다음카페', topic: 'it', category: '인터넷 서비스', hint: '주제별로 모였다', aliases: [] },
  { word: '블로그', topic: 'it', category: '인터넷 서비스', hint: '글을 올리는 개인 공간', aliases: [] },
  { word: '트위터', topic: 'it', category: '인터넷 서비스', hint: '짧은 글을 올렸다', aliases: [] },
  { word: '카카오톡', topic: 'it', category: '인터넷 서비스', hint: '2010년에 나왔다', aliases: ['카톡'] },
  { word: '윈도구팔', topic: 'it', category: '그때 그 컴퓨터', hint: '시작 버튼이 생긴 운영체제', aliases: ['윈도95', '윈도우95'] },
  { word: '도스', topic: 'it', category: '그때 그 컴퓨터', hint: '까만 화면에 명령어를 쳤다', aliases: ['DOS'] },
  { word: '아래아한글', topic: 'it', category: '그때 그 컴퓨터', hint: '국산 문서 프로그램', aliases: ['한글97', '한컴오피스'] },
  { word: '시디롬', topic: 'it', category: '그때 그 컴퓨터', hint: '원반을 넣어 읽었다', aliases: ['CD롬'] },
  { word: '그래픽카드', topic: 'it', category: '그때 그 컴퓨터', hint: '화면을 그려주는 부품', aliases: [] },
  { word: '시피유', topic: 'it', category: '그때 그 컴퓨터', hint: '컴퓨터의 두뇌라 불린다', aliases: ['CPU'] },
  { word: '램', topic: 'it', category: '그때 그 컴퓨터', hint: '전원이 꺼지면 지워진다', aliases: ['RAM'] },
  { word: '아이엠에프', topic: 'economy', category: '경제 사건', hint: '1997년 구제금융', aliases: ['IMF'] },
  { word: '금모으기운동', topic: 'economy', category: '경제 사건', hint: '집에 있던 금을 내놨다', aliases: ['금모으기'] },
  { word: '외환위기', topic: 'economy', category: '경제 사건', hint: '환율이 급등했다', aliases: [] },
  { word: '벤처붐', topic: 'economy', category: '경제 사건', hint: '2000년 전후 창업 열풍', aliases: [] },
  { word: '닷컴버블', topic: 'economy', category: '경제 사건', hint: '인터넷 기업 주가가 급등락했다', aliases: [] },
  { word: '리먼사태', topic: 'economy', category: '경제 사건', hint: '2008년 금융위기의 계기', aliases: ['리먼브라더스'] },
  { word: '구조조정', topic: 'economy', category: '경제 사건', hint: '기업이 인력을 줄였다', aliases: [] },
  { word: '명예퇴직', topic: 'economy', category: '경제 사건', hint: '정년 전에 회사를 떠났다', aliases: [] },
  { word: '부도', topic: 'economy', category: '경제 사건', hint: '어음을 막지 못하는 상태', aliases: [] },
  { word: '금융실명제', topic: 'economy', category: '경제 사건', hint: '1993년 실제 이름으로만 거래하게 했다', aliases: [] },
  { word: '경제협력개발기구', topic: 'economy', category: '경제 사건', hint: '1996년에 가입했다', aliases: ['OECD'] },
  { word: '주택청약', topic: 'economy', category: '경제 용어', hint: '통장을 만들어 순위를 쌓는다', aliases: ['청약'] },
  { word: '코스닥', topic: 'economy', category: '경제 용어', hint: '벤처 기업이 주로 상장했다', aliases: [] },
  { word: '코스피', topic: 'economy', category: '경제 용어', hint: '국내 대표 주가지수', aliases: [] },
  { word: '환율', topic: 'economy', category: '경제 용어', hint: '다른 나라 돈과 바꾸는 비율', aliases: [] },
  { word: '물가', topic: 'economy', category: '경제 용어', hint: '상품과 서비스의 값', aliases: [] },
  { word: '최저임금', topic: 'economy', category: '경제 용어', hint: '법으로 정한 시간당 하한', aliases: [] },
  { word: '부가가치세', topic: 'economy', category: '경제 용어', hint: '물건값에 붙는 세금', aliases: ['부가세'] },
  { word: '적금', topic: 'economy', category: '경제 용어', hint: '매달 넣어 만기에 받는다', aliases: [] },
  { word: '인플레이션', topic: 'economy', category: '경제 용어', hint: '물가가 지속적으로 오른다', aliases: [] },
  { word: '국내총생산', topic: 'economy', category: '경제 용어', hint: '한 해 만들어낸 부가가치의 합', aliases: ['GDP'] },
  { word: '지방자치제', topic: 'society', category: '제도', hint: '1995년 단체장 선거가 부활했다', aliases: ['지방자치'] },
  { word: '주오일제', topic: 'society', category: '제도', hint: '토요일에 쉬게 됐다', aliases: ['주5일제'] },
  { word: '국민학교', topic: 'society', category: '제도', hint: '1996년에 이름이 바뀌었다', aliases: [] },
  { word: '수학능력시험', topic: 'society', category: '제도', hint: '1994년에 처음 치렀다', aliases: ['수능'] },
  { word: '의무교육', topic: 'society', category: '제도', hint: '일정 기간 학교에 다녀야 한다', aliases: [] },
  { word: '국민연금', topic: 'society', category: '제도', hint: '노후에 받는 연금 제도', aliases: [] },
  { word: '건강보험', topic: 'society', category: '제도', hint: '병원비를 나눠 부담한다', aliases: [] },
  { word: '주민등록증', topic: 'society', category: '제도', hint: '성인이 되면 발급받는다', aliases: [] },
  { word: '호주제', topic: 'society', category: '제도', hint: '2008년에 폐지됐다', aliases: [] },
  { word: '성수대교', topic: 'society', category: '그때 그 사건', hint: '1994년에 무너졌다', aliases: [] },
  { word: '삼풍백화점', topic: 'society', category: '그때 그 사건', hint: '1995년에 붕괴했다', aliases: ['삼풍'] },
  { word: '대구지하철참사', topic: 'society', category: '그때 그 사건', hint: '2003년에 있었다', aliases: [] },
  { word: '태안기름유출', topic: 'society', category: '그때 그 사건', hint: '2007년 서해가 오염됐다', aliases: [] },
  { word: '숭례문화재', topic: 'society', category: '그때 그 사건', hint: '2008년 국보가 불탔다', aliases: ['숭례문'] },
  { word: '서울올림픽', topic: 'society', category: '그때 그 사건', hint: '1988년에 열렸다', aliases: [] },
  { word: '한일월드컵', topic: 'society', category: '그때 그 사건', hint: '2002년 공동 개최', aliases: [] },
  { word: '훈민정음', topic: 'history', category: '조선', hint: '세종이 반포했다', aliases: [] },
  { word: '거북선', topic: 'history', category: '조선', hint: '이순신이 이끌었다', aliases: [] },
  { word: '경국대전', topic: 'history', category: '조선', hint: '조선의 기본 법전', aliases: [] },
  { word: '집현전', topic: 'history', category: '조선', hint: '세종이 학자를 모은 기관', aliases: [] },
  { word: '임진왜란', topic: 'history', category: '조선', hint: '1592년에 시작됐다', aliases: [] },
  { word: '병자호란', topic: 'history', category: '조선', hint: '남한산성으로 피란했다', aliases: [] },
  { word: '대동법', topic: 'history', category: '조선', hint: '공납을 쌀로 통일했다', aliases: [] },
  { word: '탕평책', topic: 'history', category: '조선', hint: '붕당의 균형을 꾀했다', aliases: [] },
  { word: '규장각', topic: 'history', category: '조선', hint: '정조가 세운 왕실 도서관', aliases: [] },
  { word: '수원화성', topic: 'history', category: '조선', hint: '정조가 쌓은 성', aliases: [] },
  { word: '실학', topic: 'history', category: '조선', hint: '현실 문제를 다룬 학문', aliases: [] },
  { word: '한산도대첩', topic: 'history', category: '조선', hint: '학익진으로 이겼다', aliases: [] },
  { word: '명량대첩', topic: 'history', category: '조선', hint: '열두 척으로 싸웠다', aliases: [] },
  { word: '조선왕조실록', topic: 'history', category: '조선', hint: '왕의 기록을 남긴 책', aliases: [] },
  { word: '동의보감', topic: 'history', category: '조선', hint: '허준이 편찬했다', aliases: [] },
  { word: '동학농민운동', topic: 'history', category: '근대', hint: '1894년 전봉준이 이끌었다', aliases: ['동학운동'] },
  { word: '삼일운동', topic: 'history', category: '근대', hint: '1919년 독립 만세', aliases: ['3·1운동'] },
  { word: '광복절', topic: 'history', category: '근대', hint: '8월 15일', aliases: [] },
  { word: '강화도조약', topic: 'history', category: '근대', hint: '1876년 개항의 계기', aliases: [] },
  { word: '갑오개혁', topic: 'history', category: '근대', hint: '신분제를 폐지했다', aliases: [] },
  { word: '을사늑약', topic: 'history', category: '근대', hint: '1905년 외교권을 빼앗겼다', aliases: [] },
  { word: '대한민국임시정부', topic: 'history', category: '근대', hint: '상하이에서 세워졌다', aliases: ['임시정부'] },
  { word: '청산리대첩', topic: 'history', category: '근대', hint: '김좌진이 이끌었다', aliases: [] },
  { word: '안중근', topic: 'history', category: '근대', hint: '하얼빈에서 이토를 저격했다', aliases: [] },
  { word: '유관순', topic: 'history', category: '근대', hint: '아우내 장터에서 만세를 불렀다', aliases: [] },
  { word: '윤봉길', topic: 'history', category: '근대', hint: '상하이 훙커우 공원 의거', aliases: [] },
  { word: '독립문', topic: 'history', category: '근대', hint: '자주 독립을 상징한다', aliases: [] },
  { word: '새마을운동', topic: 'history', category: '현대', hint: '1970년대 농촌 근대화', aliases: [] },
  { word: '한국전쟁', topic: 'history', category: '현대', hint: '1950년에 일어났다', aliases: ['육이오', '6·25'] },
  { word: '휴전협정', topic: 'history', category: '현대', hint: '1953년에 맺어졌다', aliases: [] },
  { word: '사일구혁명', topic: 'history', category: '현대', hint: '1960년 학생이 일어섰다', aliases: ['4·19', '사일구'] },
  { word: '오일팔민주화운동', topic: 'history', category: '현대', hint: '1980년 광주에서 있었다', aliases: ['5·18', '오일팔'] },
  { word: '유월민주항쟁', topic: 'history', category: '현대', hint: '1987년 직선제를 이끌어냈다', aliases: ['6월항쟁', '유월항쟁'] },
  { word: '경부고속도로', topic: 'history', category: '현대', hint: '1970년에 개통했다', aliases: [] },
  { word: '포항제철', topic: 'history', category: '현대', hint: '산업화의 상징이었다', aliases: [] },
  { word: '남북정상회담', topic: 'history', category: '현대', hint: '2000년에 처음 열렸다', aliases: [] },
  { word: '르네상스', topic: 'world', category: '유럽사', hint: '고전의 부활', aliases: [] },
  { word: '산업혁명', topic: 'world', category: '유럽사', hint: '증기기관에서 시작됐다', aliases: [] },
  { word: '프랑스혁명', topic: 'world', category: '유럽사', hint: '바스티유 감옥 습격', aliases: [] },
  { word: '종교개혁', topic: 'world', category: '유럽사', hint: '루터가 95개조를 붙였다', aliases: [] },
  { word: '나폴레옹', topic: 'world', category: '유럽사', hint: '워털루에서 패배했다', aliases: [] },
  { word: '로마제국', topic: 'world', category: '유럽사', hint: '모든 길이 이곳으로 통했다', aliases: [] },
  { word: '십자군', topic: 'world', category: '유럽사', hint: '성지 회복을 내세웠다', aliases: [] },
  { word: '대항해시대', topic: 'world', category: '유럽사', hint: '새로운 항로를 찾아 나섰다', aliases: [] },
  { word: '흑사병', topic: 'world', category: '유럽사', hint: '중세 유럽 인구를 크게 줄였다', aliases: [] },
  { word: '베를린장벽', topic: 'world', category: '세계 현대사', hint: '1989년에 무너졌다', aliases: [] },
  { word: '아폴로십일호', topic: 'world', category: '세계 현대사', hint: '1969년 달에 착륙했다', aliases: ['아폴로11호'] },
  { word: '제일차세계대전', topic: 'world', category: '세계 현대사', hint: '1914년에 시작됐다', aliases: ['1차대전', '제1차세계대전'] },
  { word: '제이차세계대전', topic: 'world', category: '세계 현대사', hint: '1939년에 시작됐다', aliases: ['2차대전', '제2차세계대전'] },
  { word: '냉전', topic: 'world', category: '세계 현대사', hint: '미국과 소련이 대립했다', aliases: [] },
  { word: '소련해체', topic: 'world', category: '세계 현대사', hint: '1991년에 무너졌다', aliases: [] },
  { word: '구일일테러', topic: 'world', category: '세계 현대사', hint: '2001년 뉴욕에서 일어났다', aliases: ['9·11', '911테러'] },
  { word: '국제연합', topic: 'world', category: '세계 현대사', hint: '1945년에 창설됐다', aliases: ['UN', '유엔'] },
  { word: '베트남전쟁', topic: 'world', category: '세계 현대사', hint: '미국이 오래 개입했다', aliases: [] },
  { word: '독일통일', topic: 'world', category: '세계 현대사', hint: '1990년에 이뤄졌다', aliases: [] },
  { word: '콜럼버스', topic: 'world', category: '세계사 인물', hint: '1492년 항해', aliases: [] },
  { word: '간디', topic: 'world', category: '세계사 인물', hint: '비폭력 저항을 이끌었다', aliases: [] },
  { word: '아인슈타인', topic: 'world', category: '세계사 인물', hint: '상대성이론을 세웠다', aliases: [] },
  { word: '뉴턴', topic: 'world', category: '세계사 인물', hint: '만유인력을 정리했다', aliases: [] },
  { word: '다윈', topic: 'world', category: '세계사 인물', hint: '종의 기원을 썼다', aliases: [] },
  { word: '링컨', topic: 'world', category: '세계사 인물', hint: '노예 해방을 선언했다', aliases: [] },
  { word: '처칠', topic: 'world', category: '세계사 인물', hint: '2차대전 영국을 이끌었다', aliases: [] },
  { word: '셰익스피어', topic: 'world', category: '세계사 인물', hint: '햄릿을 썼다', aliases: [] },
  { word: '베토벤', topic: 'world', category: '세계사 인물', hint: '운명 교향곡을 썼다', aliases: [] },
  { word: '만델라', topic: 'world', category: '세계사 인물', hint: '남아프리카 대통령이 됐다', aliases: [] },
  { word: '칭기즈칸', topic: 'world', category: '세계사 인물', hint: '대제국을 세웠다', aliases: [] },
  { word: '차범근', topic: 'football', category: '축구 인물', hint: '독일 분데스리가에서 뛰었다', aliases: [] },
  { word: '박지성', topic: 'football', category: '축구 인물', hint: '맨체스터에서 뛰었다', aliases: [] },
  { word: '손흥민', topic: 'football', category: '축구 인물', hint: '프리미어리그 득점왕', aliases: [] },
  { word: '히딩크', topic: 'football', category: '축구 인물', hint: '2002년 대표팀 감독', aliases: [] },
  { word: '홍명보', topic: 'football', category: '축구 인물', hint: '2002년 주장이었다', aliases: [] },
  { word: '안정환', topic: 'football', category: '축구 인물', hint: '반지 세리머니로 유명하다', aliases: [] },
  { word: '이영표', topic: 'football', category: '축구 인물', hint: '왼쪽 측면 수비수였다', aliases: [] },
  { word: '김민재', topic: 'football', category: '축구 인물', hint: '수비수로 유럽에서 뛴다', aliases: [] },
  { word: '이강인', topic: 'football', category: '축구 인물', hint: '왼발이 좋은 미드필더', aliases: [] },
  { word: '황희찬', topic: 'football', category: '축구 인물', hint: '유럽에서 뛰는 공격수', aliases: [] },
  { word: '펠레', topic: 'football', category: '축구 인물', hint: '축구 황제로 불렸다', aliases: [] },
  { word: '마라도나', topic: 'football', category: '축구 인물', hint: '신의 손으로 알려졌다', aliases: [] },
  { word: '메시', topic: 'football', category: '축구 인물', hint: '아르헨티나 대표팀 주장', aliases: [] },
  { word: '호날두', topic: 'football', category: '축구 인물', hint: '포르투갈 대표팀 공격수', aliases: [] },
  { word: '베컴', topic: 'football', category: '축구 인물', hint: '프리킥이 유명했다', aliases: [] },
  { word: '지단', topic: 'football', category: '축구 인물', hint: '머리로 받은 결승이 유명하다', aliases: [] },
  { word: '오프사이드', topic: 'football', category: '축구 용어', hint: '앞서 있으면 반칙이다', aliases: [] },
  { word: '페널티킥', topic: 'football', category: '축구 용어', hint: '12야드에서 찬다', aliases: [] },
  { word: '프리킥', topic: 'football', category: '축구 용어', hint: '벽을 세우고 찬다', aliases: [] },
  { word: '코너킥', topic: 'football', category: '축구 용어', hint: '구석에서 올린다', aliases: [] },
  { word: '해트트릭', topic: 'football', category: '축구 용어', hint: '한 경기 세 골', aliases: [] },
  { word: '골키퍼', topic: 'football', category: '축구 용어', hint: '손을 쓸 수 있는 유일한 자리', aliases: [] },
  { word: '스트라이커', topic: 'football', category: '축구 용어', hint: '최전방 공격수', aliases: [] },
  { word: '미드필더', topic: 'football', category: '축구 용어', hint: '중원을 맡는다', aliases: [] },
  { word: '센터백', topic: 'football', category: '축구 용어', hint: '중앙 수비수', aliases: [] },
  { word: '레드카드', topic: 'football', category: '축구 용어', hint: '바로 퇴장이다', aliases: [] },
  { word: '옐로카드', topic: 'football', category: '축구 용어', hint: '두 장이면 퇴장', aliases: [] },
  { word: '연장전', topic: 'football', category: '축구 용어', hint: '정규 시간에 못 끝냈다', aliases: [] },
  { word: '승부차기', topic: 'football', category: '축구 용어', hint: '마지막 수단이다', aliases: [] },
  { word: '월드컵', topic: 'football', category: '축구 대회·팀', hint: '4년마다 열린다', aliases: [] },
  { word: '한일월드컵', topic: 'football', category: '축구 대회·팀', hint: '2002년 공동 개최', aliases: [] },
  { word: '케이리그', topic: 'football', category: '축구 대회·팀', hint: '국내 프로 축구 리그', aliases: ['K리그'] },
  { word: '프리미어리그', topic: 'football', category: '축구 대회·팀', hint: '잉글랜드 최상위 리그', aliases: [] },
  { word: '분데스리가', topic: 'football', category: '축구 대회·팀', hint: '독일 최상위 리그', aliases: [] },
  { word: '챔피언스리그', topic: 'football', category: '축구 대회·팀', hint: '유럽 클럽 최강전', aliases: [] },
  { word: '붉은악마', topic: 'football', category: '축구 대회·팀', hint: '대표팀 응원단', aliases: [] },
  { word: '오필승코리아', topic: 'football', category: '축구 대회·팀', hint: '2002년 거리 응원가', aliases: [] },
  { word: '박찬호', topic: 'baseball', category: '야구 인물', hint: '한국인 최초 메이저리거', aliases: [] },
  { word: '선동열', topic: 'baseball', category: '야구 인물', hint: '무등산 폭격기로 불렸다', aliases: [] },
  { word: '이승엽', topic: 'baseball', category: '야구 인물', hint: '한 시즌 56홈런을 쳤다', aliases: [] },
  { word: '류현진', topic: 'baseball', category: '야구 인물', hint: '메이저리그에서 던졌다', aliases: [] },
  { word: '추신수', topic: 'baseball', category: '야구 인물', hint: '메이저리그 외야수였다', aliases: [] },
  { word: '만루홈런', topic: 'baseball', category: '야구 용어', hint: '한 방에 4점', aliases: [] },
  { word: '완봉승', topic: 'baseball', category: '야구 용어', hint: '한 점도 안 주고 이겼다', aliases: [] },
  { word: '노히트노런', topic: 'baseball', category: '야구 용어', hint: '안타를 하나도 안 맞았다', aliases: [] },
  { word: '도루', topic: 'baseball', category: '야구 용어', hint: '다음 베이스를 훔친다', aliases: [] },
  { word: '삼진', topic: 'baseball', category: '야구 용어', hint: '스트라이크 셋', aliases: [] },
  { word: '볼넷', topic: 'baseball', category: '야구 용어', hint: '볼 넷이면 걸어 나간다', aliases: [] },
  { word: '타율', topic: 'baseball', category: '야구 용어', hint: '안타를 타수로 나눈다', aliases: [] },
  { word: '마무리투수', topic: 'baseball', category: '야구 용어', hint: '마지막을 맡는다', aliases: [] },
  { word: '직구', topic: 'baseball', category: '야구 용어', hint: '가장 빠른 공', aliases: [] },
  { word: '변화구', topic: 'baseball', category: '야구 용어', hint: '휘어져 들어가는 공', aliases: [] },
  { word: '슬라이더', topic: 'baseball', category: '야구 용어', hint: '옆으로 휘는 변화구', aliases: [] },
  { word: '해태타이거즈', topic: 'baseball', category: '야구 팀·대회', hint: '90년대 최다 우승 팀', aliases: ['해태'] },
  { word: '엘지트윈스', topic: 'baseball', category: '야구 팀·대회', hint: '잠실을 쓴다', aliases: ['LG트윈스'] },
  { word: '롯데자이언츠', topic: 'baseball', category: '야구 팀·대회', hint: '부산 연고 구단', aliases: ['롯데'] },
  { word: '삼성라이온즈', topic: 'baseball', category: '야구 팀·대회', hint: '대구 연고 구단', aliases: ['삼성'] },
  { word: '두산베어스', topic: 'baseball', category: '야구 팀·대회', hint: '잠실을 함께 쓴다', aliases: ['두산'] },
  { word: '기아타이거즈', topic: 'baseball', category: '야구 팀·대회', hint: '광주 연고 구단', aliases: ['기아'] },
  { word: '한화이글스', topic: 'baseball', category: '야구 팀·대회', hint: '대전 연고 구단', aliases: ['한화'] },
  { word: '한국시리즈', topic: 'baseball', category: '야구 팀·대회', hint: '프로야구 최종 결승', aliases: [] },
  { word: '케이비오', topic: 'baseball', category: '야구 팀·대회', hint: '국내 프로야구 리그', aliases: ['KBO'] },
  { word: '메이저리그', topic: 'baseball', category: '야구 팀·대회', hint: '미국 프로야구', aliases: ['MLB'] },
  { word: '월드시리즈', topic: 'baseball', category: '야구 팀·대회', hint: '메이저리그 최종 결승', aliases: [] },
  { word: '가을야구', topic: 'baseball', category: '야구 팀·대회', hint: '포스트시즌을 부르는 말', aliases: [] },
  { word: '허재', topic: 'basketball', category: '농구 인물', hint: '농구 대통령으로 불렸다', aliases: [] },
  { word: '서장훈', topic: 'basketball', category: '농구 인물', hint: '키 큰 국내 센터였다', aliases: [] },
  { word: '이상민', topic: 'basketball', category: '농구 인물', hint: '국내 프로 가드로 유명하다', aliases: [] },
  { word: '마이클조던', topic: 'basketball', category: '농구 인물', hint: '시카고에서 뛰었다', aliases: ['조던'] },
  { word: '코비브라이언트', topic: 'basketball', category: '농구 인물', hint: 'LA 레이커스 전설', aliases: ['코비'] },
  { word: '르브론제임스', topic: 'basketball', category: '농구 인물', hint: '현대 NBA 대표 선수', aliases: ['르브론'] },
  { word: '덩크슛', topic: 'basketball', category: '농구 용어', hint: '림에 내리꽂는다', aliases: ['덩크'] },
  { word: '레이업', topic: 'basketball', category: '농구 용어', hint: '골밑에 살짝 올린다', aliases: [] },
  { word: '삼점슛', topic: 'basketball', category: '농구 용어', hint: '아크 밖에서 넣는다', aliases: ['3점슛'] },
  { word: '자유투', topic: 'basketball', category: '농구 용어', hint: '반칙을 받아 혼자 던진다', aliases: [] },
  { word: '리바운드', topic: 'basketball', category: '농구 용어', hint: '튀어나온 공을 잡는다', aliases: [] },
  { word: '어시스트', topic: 'basketball', category: '농구 용어', hint: '득점을 도왔다', aliases: [] },
  { word: '스틸', topic: 'basketball', category: '농구 용어', hint: '공을 가로챘다', aliases: [] },
  { word: '블록슛', topic: 'basketball', category: '농구 용어', hint: '슛을 쳐냈다', aliases: [] },
  { word: '속공', topic: 'basketball', category: '농구 용어', hint: '빠르게 몰아친다', aliases: ['패스트브레이크'] },
  { word: '버저비터', topic: 'basketball', category: '농구 용어', hint: '종료 부저와 함께 들어갔다', aliases: [] },
  { word: '센터', topic: 'basketball', category: '농구 용어', hint: '골밑을 지킨다', aliases: [] },
  { word: '포인트가드', topic: 'basketball', category: '농구 용어', hint: '공을 운반한다', aliases: [] },
  { word: '케이비엘', topic: 'basketball', category: '농구 리그·문화', hint: '국내 프로 농구 리그', aliases: ['KBL'] },
  { word: '엔비에이', topic: 'basketball', category: '농구 리그·문화', hint: '미국 프로 농구', aliases: ['NBA'] },
  { word: '슬램덩크', topic: 'basketball', category: '농구 리그·문화', hint: '북산고가 나오는 농구 만화', aliases: [] },
  { word: '마지막승부', topic: 'basketball', category: '농구 리그·문화', hint: '농구 소재 드라마였다', aliases: [] },
  { word: '올스타전', topic: 'basketball', category: '농구 리그·문화', hint: '인기 선수들이 모인다', aliases: [] },
  { word: '플레이오프', topic: 'basketball', category: '농구 리그·문화', hint: '정규 시즌 다음 단계', aliases: [] },
  { word: '김연아', topic: 'sports', category: '스포츠 인물', hint: '피겨 금메달을 땄다', aliases: [] },
  { word: '박세리', topic: 'sports', category: '스포츠 인물', hint: '맨발 투혼', aliases: [] },
  { word: '황영조', topic: 'sports', category: '스포츠 인물', hint: '바르셀로나 마라톤 금메달', aliases: [] },
  { word: '장미란', topic: 'sports', category: '스포츠 인물', hint: '역도 금메달리스트', aliases: [] },
  { word: '우사인볼트', topic: 'sports', category: '스포츠 인물', hint: '단거리 세계기록 보유자', aliases: [] },
  { word: '올림픽', topic: 'sports', category: '대회·종목', hint: '4년마다 열린다', aliases: [] },
  { word: '아시안게임', topic: 'sports', category: '대회·종목', hint: '아시아 종합 대회', aliases: [] },
  { word: '평창동계올림픽', topic: 'sports', category: '대회·종목', hint: '2018년 강원도에서 열렸다', aliases: ['평창올림픽'] },
  { word: '베이징올림픽', topic: 'sports', category: '대회·종목', hint: '2008년에 열렸다', aliases: [] },
  { word: '런던올림픽', topic: 'sports', category: '대회·종목', hint: '2012년에 열렸다', aliases: [] },
  { word: '양궁', topic: 'sports', category: '대회·종목', hint: '활을 쏜다', aliases: [] },
  { word: '태권도', topic: 'sports', category: '대회·종목', hint: '우리나라에서 시작됐다', aliases: [] },
  { word: '쇼트트랙', topic: 'sports', category: '대회·종목', hint: '좁은 링크를 돈다', aliases: [] },
  { word: '스피드스케이팅', topic: 'sports', category: '대회·종목', hint: '넓은 링크를 돈다', aliases: [] },
  { word: '피겨스케이팅', topic: 'sports', category: '대회·종목', hint: '점프와 회전으로 겨룬다', aliases: [] },
  { word: '배드민턴', topic: 'sports', category: '대회·종목', hint: '셔틀콕을 친다', aliases: [] },
  { word: '마라톤', topic: 'sports', category: '대회·종목', hint: '42.195km 를 뛴다', aliases: [] },
  { word: '철권', topic: 'game', category: '오락실 게임', hint: '발차기가 유명하다', aliases: [] },
  { word: '메탈슬러그', topic: 'game', category: '오락실 게임', hint: '총을 쏘며 전진한다', aliases: [] },
  { word: '리그오브레전드', topic: 'game', category: '온라인 게임', hint: '5대5로 싸운다', aliases: ['롤', 'LOL'] },
  { word: '오버워치', topic: 'game', category: '온라인 게임', hint: '팀 기반 슈팅 게임', aliases: [] },
  { word: '배틀그라운드', topic: 'game', category: '온라인 게임', hint: '마지막까지 살아남는다', aliases: ['배그'] },
  { word: '슈퍼마리오', topic: 'game', category: '콘솔·패키지', hint: '버섯을 먹고 커진다', aliases: ['마리오'] },
  { word: '젤다의전설', topic: 'game', category: '콘솔·패키지', hint: '링크가 주인공이다', aliases: [] },
  { word: '포켓몬스터', topic: 'game', category: '콘솔·패키지', hint: '몬스터를 잡아 키운다', aliases: ['포켓몬'] },
  { word: '플레이스테이션', topic: 'game', category: '콘솔·패키지', hint: '소니가 만든 콘솔', aliases: ['플스'] },
  { word: '닌텐도', topic: 'game', category: '콘솔·패키지', hint: '일본 게임 회사', aliases: [] },
  { word: '게임보이', topic: 'game', category: '콘솔·패키지', hint: '들고 다니는 게임기', aliases: [] },
  { word: '레벨업', topic: 'game', category: '게임 용어', hint: '경험치가 차면 오른다', aliases: [] },
  { word: '아이템', topic: 'game', category: '게임 용어', hint: '장비나 소모품', aliases: [] },
  { word: '길드', topic: 'game', category: '게임 용어', hint: '같이 노는 모임', aliases: [] },
  { word: '보스전', topic: 'game', category: '게임 용어', hint: '마지막에 큰 적이 나온다', aliases: [] },
  { word: '만렙', topic: 'game', category: '게임 용어', hint: '최고 레벨', aliases: [] },
  { word: '버그', topic: 'game', category: '게임 용어', hint: '의도치 않은 오류', aliases: [] },
  { word: '패치', topic: 'game', category: '게임 용어', hint: '고쳐서 배포한다', aliases: [] },
  { word: '나는가수다', topic: 'culture', category: '예능·방송', hint: '가수들이 순위를 매겼다', aliases: [] },
  { word: '슈퍼스타케이', topic: 'culture', category: '예능·방송', hint: '오디션 프로그램이었다', aliases: ['슈스케'] },
  { word: '복면가왕', topic: 'culture', category: '예능·방송', hint: '가면을 쓰고 노래한다', aliases: [] },
  { word: '삼시세끼', topic: 'culture', category: '예능·방송', hint: '시골에서 밥을 해 먹는다', aliases: [] },
  { word: '놀면뭐하니', topic: 'culture', category: '예능·방송', hint: '유재석이 여러 부캐를 했다', aliases: [] },
  { word: '아는형님', topic: 'culture', category: '예능·방송', hint: '교실에서 진행한다', aliases: [] },
  { word: '신서유기', topic: 'culture', category: '예능·방송', hint: '게임을 많이 한다', aliases: [] },
  { word: '불후의명곡', topic: 'culture', category: '예능·방송', hint: '명곡을 다시 부른다', aliases: [] },
  { word: '미스트롯', topic: 'culture', category: '예능·방송', hint: '트로트 오디션이었다', aliases: [] },
  { word: '금요일밤에', topic: 'culture', category: '예능·방송', hint: '예능 프로그램', aliases: [] },
  { word: '연예가중계', topic: 'culture', category: '예능·방송', hint: '연예 소식을 전했다', aliases: [] },
  { word: '둘리', topic: 'anime', category: '한국 애니', hint: '빙하를 타고 온 공룡', aliases: ['아기공룡둘리'] },
  { word: '뽀로로', topic: 'anime', category: '한국 애니', hint: '노는 게 제일 좋다', aliases: [] },
  { word: '타요', topic: 'anime', category: '한국 애니', hint: '파란 버스다', aliases: [] },
  { word: '로보카폴리', topic: 'anime', category: '한국 애니', hint: '변신하는 경찰차', aliases: [] },
  { word: '마시마로', topic: 'anime', category: '한국 애니', hint: '엽기 토끼로 불렸다', aliases: [] },
  { word: '뿌까', topic: 'anime', category: '한국 애니', hint: '빨간 옷 소녀 캐릭터', aliases: [] },
  { word: '라바', topic: 'anime', category: '한국 애니', hint: '애벌레 두 마리가 나온다', aliases: [] },
  { word: '포켓몬스터', topic: 'anime', category: '일본 애니', hint: '몬스터를 잡아 키운다', aliases: ['포켓몬'] },
  { word: '귀멸의칼날', topic: 'anime', category: '일본 애니', hint: '도깨비를 베는 검사들', aliases: [] },
  { word: '진격의거인', topic: 'anime', category: '일본 애니', hint: '벽 안에서 산다', aliases: [] },
  { word: '너의이름은', topic: 'anime', category: '일본 애니', hint: '몸이 바뀌는 이야기', aliases: [] },
  { word: '스즈메', topic: 'anime', category: '일본 애니', hint: '문을 닫으러 다닌다', aliases: [] },
  { word: '짱구', topic: 'anime', category: '일본 애니', hint: '다섯 살 개구쟁이', aliases: [] },
  { word: '수능', topic: 'society', category: '제도·사회', hint: '해마다 11월에 치른다', aliases: ['수학능력시험'] },
  { word: '민방위', topic: 'society', category: '제도·사회', hint: '훈련을 받는다', aliases: [] },
  { word: '예비군', topic: 'society', category: '제도·사회', hint: '전역 후에도 소집된다', aliases: [] },
  { word: '주민센터', topic: 'society', category: '제도·사회', hint: '동네 행정 기관이다', aliases: [] },
  { word: '택배', topic: 'society', category: '제도·사회', hint: '집까지 물건을 보내준다', aliases: [] },
  { word: '지하철', topic: 'society', category: '제도·사회', hint: '도시의 대중교통', aliases: [] },
  { word: '고속철도', topic: 'society', category: '제도·사회', hint: '서울과 부산을 빠르게 잇는다', aliases: ['KTX'] },
  { word: '인천공항', topic: 'society', category: '제도·사회', hint: '국내 최대 국제공항', aliases: [] },
  { word: '한강공원', topic: 'society', category: '제도·사회', hint: '서울 시민의 쉼터', aliases: [] },
  { word: '아파트', topic: 'society', category: '제도·사회', hint: '한국에서 가장 흔한 주거 형태', aliases: [] },
  { word: '네이버', topic: 'it', category: '인터넷·기기', hint: '국내 최대 포털', aliases: [] },
  { word: '다음', topic: 'it', category: '인터넷·기기', hint: '국내 포털 서비스', aliases: [] },
  { word: '구글', topic: 'it', category: '인터넷·기기', hint: '세계 최대 검색 엔진', aliases: [] },
  { word: '유튜브', topic: 'it', category: '인터넷·기기', hint: '동영상을 올리는 서비스', aliases: [] },
  { word: '아이폰', topic: 'it', category: '인터넷·기기', hint: '애플이 만든 스마트폰', aliases: [] },
  { word: '갤럭시', topic: 'it', category: '인터넷·기기', hint: '삼성이 만든 스마트폰', aliases: [] },
  { word: '와이파이', topic: 'it', category: '인터넷·기기', hint: '무선으로 인터넷을 쓴다', aliases: [] },
  { word: '스마트폰', topic: 'it', category: '인터넷·기기', hint: '전화기이면서 컴퓨터다', aliases: [] },
  { word: '노트북', topic: 'it', category: '인터넷·기기', hint: '들고 다니는 컴퓨터', aliases: [] },
  { word: '이메일', topic: 'it', category: '인터넷·기기', hint: '골뱅이가 들어간 주소', aliases: [] },
  { word: '인공지능', topic: 'it', category: '인터넷·기기', hint: '스스로 배우는 기술', aliases: ['AI'] },
  { word: '클라우드', topic: 'it', category: '인터넷·기기', hint: '인터넷에 저장한다', aliases: [] },
  { word: '손흥민', topic: 'sports', category: '스포츠 종합', hint: '프리미어리그 득점왕', aliases: [] },
  { word: '박찬호', topic: 'sports', category: '스포츠 종합', hint: '한국인 최초 메이저리거', aliases: [] },
  { word: '박지성', topic: 'sports', category: '스포츠 종합', hint: '맨체스터에서 뛰었다', aliases: [] },
  { word: '월드컵', topic: 'sports', category: '스포츠 종합', hint: '축구 최대 대회', aliases: [] },
  { word: '금메달', topic: 'sports', category: '스포츠 종합', hint: '1등에게 준다', aliases: [] },
  { word: '시상대', topic: 'sports', category: '스포츠 종합', hint: '메달리스트가 올라간다', aliases: [] },
  { word: '주식', topic: 'economy', category: '경제', hint: '회사의 소유권을 나눈 것', aliases: [] },
  { word: '은행', topic: 'economy', category: '경제', hint: '돈을 맡기고 빌린다', aliases: [] },
  { word: '예금', topic: 'economy', category: '경제', hint: '목돈을 맡겨 둔다', aliases: [] },
  { word: '세금', topic: 'economy', category: '경제', hint: '나라에 내는 돈', aliases: [] },
  { word: '연말정산', topic: 'economy', category: '경제', hint: '한 해 세금을 다시 계산한다', aliases: [] },
  { word: '부동산', topic: 'economy', category: '경제', hint: '땅과 건물', aliases: [] },
  { word: '전세', topic: 'economy', category: '경제', hint: '보증금을 맡기고 산다', aliases: [] },
  { word: '월세', topic: 'economy', category: '경제', hint: '다달이 내고 산다', aliases: [] },
  { word: '청약', topic: 'economy', category: '경제', hint: '집을 분양받으려고 넣는다', aliases: ['주택청약'] },
]
