import type { TopicId } from '@retro/types'
import type { NonEmptyArray } from '@retro/room-kit'

/**
 * 초성 퀴즈 문제 풀.
 *
 * **지금은 이 파일이 곧 DB다.** TypeScript 상수라 Worker 번들에 그대로 들어간다.
 * 정식 파이프라인(04 문서)에서는 여기 대신 Workers KV 를 읽고, 방 생성 시
 * 한 번 받아 DO 메모리에 들고 있는다 (05 문서 §5). `ContentPool` 이 그 자리다 —
 * 풀이 비어 있을 때만 아래 상수로 떨어진다.
 *
 * `topic` 은 시대와 직교한다. 「90년대 IT」도 「세계사」도 같은 구조에 들어간다.
 */

export interface ChosungWord {
  readonly word: string
  readonly topic: TopicId
  readonly category: string
  /** 8초에 공개되는 설명 한 줄 */
  readonly hint: string
  /** 사전에 등록된 다른 정답. 복수 정답 허용 — 02 문서 §2.3 */
  readonly aliases: readonly string[]
}

export const SAMPLE_WORDS: NonEmptyArray<ChosungWord> = [
  { word: '삐삐', topic: 'daily', category: '그때 그 물건', hint: '허리에 차고 다녔다', aliases: ['무선호출기'] },
  { word: '워크맨', topic: 'daily', category: '그때 그 물건', hint: '테이프를 넣고 들었다', aliases: [] },
  { word: '다마고치', topic: 'daily', category: '그때 그 물건', hint: '밥 안 주면 죽었다', aliases: [] },
  { word: '브로마이드', topic: 'daily', category: '그때 그 물건', hint: '벽에 붙이던 대형 사진', aliases: [] },
  { word: '시티폰', topic: 'daily', category: '그때 그 물건', hint: '발신만 되던 전화', aliases: [] },
  { word: '공중전화', topic: 'daily', category: '그때 그 물건', hint: '카드나 동전을 넣었다', aliases: [] },
  { word: '카세트테이프', topic: 'daily', category: '그때 그 물건', hint: '연필로 감았다', aliases: ['카세트'] },
  { word: '플로피디스켓', topic: 'daily', category: '그때 그 물건', hint: '1.44MB 였다', aliases: ['디스켓'] },
  { word: '전화카드', topic: 'daily', category: '그때 그 물건', hint: '공중전화에 꽂아 썼다', aliases: [] },
  { word: '버스토큰', topic: 'daily', category: '그때 그 물건', hint: '버스 탈 때 통에 넣었다', aliases: [] },
  { word: '필름카메라', topic: 'daily', category: '그때 그 물건', hint: '현상소에 맡겨야 볼 수 있었다', aliases: [] },
  { word: '일회용카메라', topic: 'daily', category: '그때 그 물건', hint: '한 번 쓰고 통째로 맡겼다', aliases: [] },
  { word: '시디플레이어', topic: 'daily', category: '그때 그 물건', hint: '원반을 넣어 돌렸다', aliases: ['CD플레이어'] },
  { word: '엠피삼', topic: 'daily', category: '그때 그 물건', hint: '노래를 넣어 다녔다', aliases: ['MP3', '엠피쓰리'] },
  { word: '전자수첩', topic: 'daily', category: '그때 그 물건', hint: '주소와 일정을 넣었다', aliases: [] },
  { word: '연탄', topic: 'daily', category: '그때 그 물건', hint: '아궁이에 넣고 갈았다', aliases: [] },
  { word: '곤로', topic: 'daily', category: '그때 그 물건', hint: '석유를 넣어 불을 켰다', aliases: [] },
  { word: '책받침', topic: 'daily', category: '그때 그 물건', hint: '연예인 사진이 들어 있었다', aliases: [] },
  { word: '샤프', topic: 'daily', category: '그때 그 물건', hint: '심을 넣어 쓰는 필기구', aliases: [] },
  { word: '색종이', topic: 'daily', category: '그때 그 물건', hint: '접어서 학을 만들었다', aliases: [] },
  { word: '브이에이치에스', topic: 'daily', category: '그때 그 물건', hint: '네모난 비디오 테이프', aliases: ['VHS', '비디오테이프'] },
  { word: '턴테이블', topic: 'daily', category: '그때 그 물건', hint: '바늘을 올려 판을 돌렸다', aliases: [] },
  { word: '전축', topic: 'daily', category: '그때 그 물건', hint: '거실 한가운데 있었다', aliases: [] },
  { word: '선풍기', topic: 'daily', category: '그때 그 물건', hint: '여름에 목을 돌렸다', aliases: [] },
  { word: '다이얼전화', topic: 'daily', category: '그때 그 물건', hint: '손가락을 넣어 돌렸다', aliases: [] },
  { word: '타자기', topic: 'daily', category: '그때 그 물건', hint: '종이를 끼우고 두드렸다', aliases: [] },
  { word: '호출기', topic: 'daily', category: '그때 그 물건', hint: '숫자로 신호를 받았다', aliases: [] },
  { word: '보온도시락', topic: 'daily', category: '그때 그 물건', hint: '겨울에 따뜻했다', aliases: [] },
  { word: '양은도시락', topic: 'daily', category: '그때 그 물건', hint: '난로 위에 올려 뒀다', aliases: [] },
  { word: '교련복', topic: 'daily', category: '그때 그 물건', hint: '학교에서 입던 얼룩무늬', aliases: [] },
  { word: '실내화', topic: 'daily', category: '그때 그 물건', hint: '학교에서 갈아 신었다', aliases: [] },
  { word: '가정통신문', topic: 'daily', category: '그때 그 물건', hint: '부모님 도장을 받아 갔다', aliases: [] },
  { word: '성적표', topic: 'daily', category: '그때 그 물건', hint: '봉투에 담겨 왔다', aliases: [] },
  { word: '문방구', topic: 'daily', category: '그때 그 장소', hint: '학교 앞에 꼭 있었다', aliases: [] },
  { word: '오락실', topic: 'daily', category: '그때 그 장소', hint: '동전을 쌓아두고 줄을 섰다', aliases: [] },
  { word: '만화방', topic: 'daily', category: '그때 그 장소', hint: '라면도 팔았다', aliases: ['만화가게'] },
  { word: '비디오가게', topic: 'daily', category: '그때 그 장소', hint: '연체료가 무서웠다', aliases: ['비디오대여점'] },
  { word: '롤라장', topic: 'daily', category: '그때 그 장소', hint: '바퀴 달린 신발을 빌렸다', aliases: ['롤러장'] },
  { word: '피시방', topic: 'daily', category: '그때 그 장소', hint: '시간당 천 원이었다', aliases: ['PC방'] },
  { word: '노래방', topic: 'daily', category: '그때 그 장소', hint: '한 곡에 얼마씩 받았다', aliases: [] },
  { word: '구멍가게', topic: 'daily', category: '그때 그 장소', hint: '동네 골목에 있었다', aliases: [] },
  { word: '학교매점', topic: 'daily', category: '그때 그 장소', hint: '종 치면 뛰어갔다', aliases: [] },
  { word: '공중목욕탕', topic: 'daily', category: '그때 그 장소', hint: '때를 밀어주는 사람이 있었다', aliases: ['목욕탕'] },
  { word: '레코드가게', topic: 'daily', category: '그때 그 장소', hint: '앨범을 사러 갔다', aliases: [] },
  { word: '사진관', topic: 'daily', category: '그때 그 장소', hint: '증명사진을 찍었다', aliases: [] },
  { word: '컴퓨터학원', topic: 'daily', category: '그때 그 장소', hint: '워드프로세서 자격증을 땄다', aliases: [] },
  { word: '독서실', topic: 'daily', category: '그때 그 장소', hint: '칸막이 책상이 있었다', aliases: [] },
  { word: '만화대여점', topic: 'daily', category: '그때 그 장소', hint: '권당 얼마씩 빌렸다', aliases: [] },
  { word: '전당포', topic: 'daily', category: '그때 그 장소', hint: '물건을 맡기고 돈을 빌렸다', aliases: [] },
  { word: '다방', topic: 'daily', category: '그때 그 장소', hint: '계란 노른자를 띄워 줬다', aliases: [] },
  { word: '분식집', topic: 'daily', category: '그때 그 장소', hint: '떡볶이와 순대를 팔았다', aliases: [] },
  { word: '구내식당', topic: 'daily', category: '그때 그 장소', hint: '식권을 냈다', aliases: [] },
  { word: '놀이터', topic: 'daily', category: '그때 그 장소', hint: '모래밭에 미끄럼틀이 있었다', aliases: [] },
  { word: '죠스바', topic: 'daily', category: '그때 그 군것질', hint: '혀가 파래졌다', aliases: [] },
  { word: '쌍쌍바', topic: 'daily', category: '그때 그 군것질', hint: '반으로 쪼개 나눠 먹었다', aliases: [] },
  { word: '뽀빠이', topic: 'daily', category: '그때 그 군것질', hint: '별사탕이 들어 있었다', aliases: [] },
  { word: '새우깡', topic: 'daily', category: '그때 그 군것질', hint: '손이 가요 손이 가', aliases: [] },
  { word: '자야', topic: 'daily', category: '그때 그 군것질', hint: '땅콩이 박힌 과자', aliases: [] },
  { word: '빠삐코', topic: 'daily', category: '그때 그 군것질', hint: '튜브를 짜서 먹었다', aliases: [] },
  { word: '메로나', topic: 'daily', category: '그때 그 군것질', hint: '연두색 아이스크림', aliases: [] },
  { word: '바밤바', topic: 'daily', category: '그때 그 군것질', hint: '밤 맛이 났다', aliases: [] },
  { word: '누가바', topic: 'daily', category: '그때 그 군것질', hint: '겉은 초코 속은 아이스크림', aliases: [] },
  { word: '스크류바', topic: 'daily', category: '그때 그 군것질', hint: '꼬여 있는 모양', aliases: [] },
  { word: '밀키스', topic: 'daily', category: '그때 그 군것질', hint: '우유가 들어간 탄산', aliases: [] },
  { word: '맥콜', topic: 'daily', category: '그때 그 군것질', hint: '보리로 만든 탄산', aliases: [] },
  { word: '쿠쿠다스', topic: 'daily', category: '그때 그 군것질', hint: '부서지기 쉬웠다', aliases: [] },
  { word: '초코파이', topic: 'daily', category: '그때 그 군것질', hint: '정을 나눴다', aliases: [] },
  { word: '건빵', topic: 'daily', category: '그때 그 군것질', hint: '별사탕이 같이 들었다', aliases: [] },
  { word: '아폴로', topic: 'daily', category: '그때 그 군것질', hint: '빨대 모양 사탕', aliases: [] },
  { word: '쫀드기', topic: 'daily', category: '그때 그 군것질', hint: '불에 구워 먹었다', aliases: [] },
  { word: '달고나', topic: 'daily', category: '그때 그 군것질', hint: '국자에 설탕을 녹였다', aliases: ['뽑기'] },
  { word: '라면땅', topic: 'daily', category: '그때 그 군것질', hint: '부숴 먹는 과자', aliases: [] },
  { word: '꾀돌이', topic: 'daily', category: '그때 그 군것질', hint: '땅콩이 든 초콜릿', aliases: [] },
  { word: '아이스께끼', topic: 'daily', category: '그때 그 군것질', hint: '통을 메고 팔러 다녔다', aliases: [] },
  { word: '번데기', topic: 'daily', category: '그때 그 군것질', hint: '종이컵에 담아 팔았다', aliases: [] },
  { word: '솜사탕', topic: 'daily', category: '그때 그 군것질', hint: '막대에 감아 줬다', aliases: [] },
  { word: '호빵', topic: 'daily', category: '그때 그 군것질', hint: '겨울에 김이 났다', aliases: [] },
  { word: '딱지치기', topic: 'daily', category: '그때 그 놀이', hint: '땅에 쳐서 뒤집었다', aliases: ['딱지'] },
  { word: '구슬치기', topic: 'daily', category: '그때 그 놀이', hint: '유리알로 하는 놀이', aliases: [] },
  { word: '고무줄놀이', topic: 'daily', category: '그때 그 놀이', hint: '다리에 걸고 넘었다', aliases: [] },
  { word: '공기놀이', topic: 'daily', category: '그때 그 놀이', hint: '다섯 알을 던져 받았다', aliases: ['공기'] },
  { word: '숨바꼭질', topic: 'daily', category: '그때 그 놀이', hint: '술래가 눈을 감고 셌다', aliases: [] },
  { word: '말뚝박기', topic: 'daily', category: '그때 그 놀이', hint: '등에 올라탔다', aliases: [] },
  { word: '오징어게임', topic: 'daily', category: '그때 그 놀이', hint: '땅에 그림을 그리고 했다', aliases: [] },
  { word: '비석치기', topic: 'daily', category: '그때 그 놀이', hint: '돌을 세워 맞췄다', aliases: [] },
  { word: '제기차기', topic: 'daily', category: '그때 그 놀이', hint: '발등으로 찼다', aliases: [] },
  { word: '팽이치기', topic: 'daily', category: '그때 그 놀이', hint: '줄을 감아 던졌다', aliases: [] },
  { word: '무궁화꽃', topic: 'daily', category: '그때 그 놀이', hint: '뒤돌아보면 멈춰야 했다', aliases: [] },
  { word: '사방치기', topic: 'daily', category: '그때 그 놀이', hint: '칸을 뛰어넘었다', aliases: [] },
  { word: '야타족', topic: 'daily', category: '그때 그 유행', hint: '차에 타라고 불렀다', aliases: [] },
  { word: '오빠믿지', topic: 'daily', category: '그때 그 유행', hint: '믿으면 안 됐다', aliases: [] },
  { word: '무스탕', topic: 'daily', category: '그때 그 유행', hint: '겨울에 유행한 외투', aliases: [] },
  { word: '힙합바지', topic: 'daily', category: '그때 그 유행', hint: '통이 아주 넓었다', aliases: [] },
  { word: '떡볶이코트', topic: 'daily', category: '그때 그 유행', hint: '단추가 나무였다', aliases: [] },
  { word: '컬러링', topic: 'daily', category: '그때 그 유행', hint: '전화를 걸면 노래가 나왔다', aliases: [] },
  { word: '폴더폰', topic: 'daily', category: '그때 그 유행', hint: '접었다 폈다 했다', aliases: [] },
  { word: '배꼽티', topic: 'daily', category: '그때 그 유행', hint: '짧은 상의였다', aliases: [] },
  { word: '통굽구두', topic: 'daily', category: '그때 그 유행', hint: '밑창이 아주 두꺼웠다', aliases: [] },
  { word: '삼단가방', topic: 'daily', category: '그때 그 유행', hint: '칸이 나뉜 책가방', aliases: [] },
  { word: '모래시계', topic: 'culture', category: '드라마·예능', hint: '나 지금 떨고 있니', aliases: [] },
  { word: '순풍산부인과', topic: 'culture', category: '드라마·예능', hint: '미달이가 나왔다', aliases: ['순풍'] },
  { word: '전원일기', topic: 'culture', category: '드라마·예능', hint: '20년 넘게 방영된 농촌 드라마', aliases: [] },
  { word: '가요톱텐', topic: 'culture', category: '드라마·예능', hint: '5주 연속 1위면 골든컵', aliases: [] },
  { word: '사랑이뭐길래', topic: 'culture', category: '드라마·예능', hint: '대발이가 나왔다', aliases: [] },
  { word: '여명의눈동자', topic: 'culture', category: '드라마·예능', hint: '일제강점기를 다뤘다', aliases: [] },
  { word: '허준', topic: 'culture', category: '드라마·예능', hint: '의학 사극이었다', aliases: [] },
  { word: '대장금', topic: 'culture', category: '드라마·예능', hint: '궁중 요리를 다룬 사극', aliases: [] },
  { word: '겨울연가', topic: 'culture', category: '드라마·예능', hint: '한류의 출발점으로 꼽힌다', aliases: [] },
  { word: '별은내가슴에', topic: 'culture', category: '드라마·예능', hint: '재벌과 신인의 이야기', aliases: [] },
  { word: '내이름은김삼순', topic: 'culture', category: '드라마·예능', hint: '제빵사가 주인공이었다', aliases: [] },
  { word: '무한도전', topic: 'culture', category: '드라마·예능', hint: '평균 이하를 표방했다', aliases: [] },
  { word: '일요일일요일밤에', topic: 'culture', category: '드라마·예능', hint: '주말 예능의 대표였다', aliases: [] },
  { word: '토요미스테리', topic: 'culture', category: '드라마·예능', hint: '무서운 이야기를 다뤘다', aliases: [] },
  { word: '추적육십분', topic: 'culture', category: '드라마·예능', hint: '시사 고발 프로그램이다', aliases: ['추적60분'] },
  { word: '열린음악회', topic: 'culture', category: '드라마·예능', hint: '야외 무대에서 열렸다', aliases: [] },
  { word: '개그콘서트', topic: 'culture', category: '드라마·예능', hint: '공개 코미디 프로그램', aliases: [] },
  { word: '상상플러스', topic: 'culture', category: '드라마·예능', hint: '세대 차이를 다룬 예능', aliases: [] },
  { word: '서태지와아이들', topic: 'culture', category: '그때 그 가수', hint: '「난 알아요」 로 데뷔했다', aliases: ['서태지'] },
  { word: '핑클', topic: 'culture', category: '그때 그 가수', hint: '4인조 여성 그룹', aliases: [] },
  { word: '에이치오티', topic: 'culture', category: '그때 그 가수', hint: '흰 풍선을 흔들었다', aliases: ['HOT', 'H.O.T'] },
  { word: '젝스키스', topic: 'culture', category: '그때 그 가수', hint: '노란 풍선이었다', aliases: ['젝키'] },
  { word: '에스이에스', topic: 'culture', category: '그때 그 가수', hint: '3인조 여성 그룹이었다', aliases: ['SES', 'S.E.S'] },
  { word: '신화', topic: 'culture', category: '그때 그 가수', hint: '장수 아이돌 그룹', aliases: [] },
  { word: '지오디', topic: 'culture', category: '그때 그 가수', hint: '「어머님께」 를 불렀다', aliases: ['god'] },
  { word: '김건모', topic: 'culture', category: '그때 그 가수', hint: '「잘못된 만남」 을 불렀다', aliases: [] },
  { word: '룰라', topic: 'culture', category: '그때 그 가수', hint: '「날개 잃은 천사」', aliases: [] },
  { word: '클론', topic: 'culture', category: '그때 그 가수', hint: '「꿍따리 샤바라」', aliases: [] },
  { word: '디제이덕', topic: 'culture', category: '그때 그 가수', hint: '「머리 어깨 무릎 발」', aliases: ['DJ DOC'] },
  { word: '이문세', topic: 'culture', category: '그때 그 가수', hint: '「붉은 노을」 을 불렀다', aliases: [] },
  { word: '신승훈', topic: 'culture', category: '그때 그 가수', hint: '발라드의 황제로 불렸다', aliases: [] },
  { word: '조성모', topic: 'culture', category: '그때 그 가수', hint: '뮤직비디오가 영화 같았다', aliases: [] },
  { word: '부활', topic: 'culture', category: '그때 그 가수', hint: '「네버엔딩스토리」', aliases: [] },
  { word: '산울림', topic: 'culture', category: '그때 그 가수', hint: '「아니 벌써」 를 불렀다', aliases: [] },
  { word: '들국화', topic: 'culture', category: '그때 그 가수', hint: '「행진」 을 불렀다', aliases: [] },
  { word: '보아', topic: 'culture', category: '그때 그 가수', hint: '일본에서도 1위를 했다', aliases: [] },
  { word: '싸이', topic: 'culture', category: '그때 그 가수', hint: '「강남스타일」 로 세계적 인기', aliases: [] },
  { word: '동방신기', topic: 'culture', category: '그때 그 가수', hint: '5인조로 데뷔했다', aliases: [] },
  { word: '빅뱅', topic: 'culture', category: '그때 그 가수', hint: '「거짓말」 이 크게 인기였다', aliases: [] },
  { word: '소녀시대', topic: 'culture', category: '그때 그 가수', hint: '9인조 여성 그룹', aliases: [] },
  { word: '원더걸스', topic: 'culture', category: '그때 그 가수', hint: '「텔미」 가 유행했다', aliases: [] },
  { word: '쉬리', topic: 'culture', category: '그때 그 영화', hint: '한국 영화 흥행 기록을 새로 썼다', aliases: [] },
  { word: '접속', topic: 'culture', category: '그때 그 영화', hint: 'PC통신으로 만나는 이야기', aliases: [] },
  { word: '엽기적인그녀', topic: 'culture', category: '그때 그 영화', hint: '지하철에서 시작됐다', aliases: [] },
  { word: '친구', topic: 'culture', category: '그때 그 영화', hint: '부산 사투리가 화제였다', aliases: [] },
  { word: '공동경비구역', topic: 'culture', category: '그때 그 영화', hint: '판문점을 배경으로 했다', aliases: ['JSA'] },
  { word: '올드보이', topic: 'culture', category: '그때 그 영화', hint: '칸 영화제에서 상을 받았다', aliases: [] },
  { word: '살인의추억', topic: 'culture', category: '그때 그 영화', hint: '미제 사건을 다뤘다', aliases: [] },
  { word: '타이타닉', topic: 'culture', category: '그때 그 영화', hint: '배가 침몰하는 이야기', aliases: [] },
  { word: '터미네이터', topic: 'culture', category: '그때 그 영화', hint: '기계와 싸운다', aliases: [] },
  { word: '쥬라기공원', topic: 'culture', category: '그때 그 영화', hint: '공룡이 되살아났다', aliases: [] },
  { word: '매트릭스', topic: 'culture', category: '그때 그 영화', hint: '빨간 약과 파란 약', aliases: [] },
  { word: '서편제', topic: 'culture', category: '그때 그 영화', hint: '판소리를 다룬 영화', aliases: [] },
  { word: '은행나무침대', topic: 'culture', category: '그때 그 영화', hint: '전생의 사랑 이야기', aliases: [] },
  { word: '편지', topic: 'culture', category: '그때 그 영화', hint: '시한부 사랑을 다뤘다', aliases: [] },
  { word: '실미도', topic: 'culture', category: '그때 그 영화', hint: '천만 관객을 처음 넘겼다', aliases: [] },
  { word: '태극기휘날리며', topic: 'culture', category: '그때 그 영화', hint: '한국전쟁 형제 이야기', aliases: [] },
  { word: '왕의남자', topic: 'culture', category: '그때 그 영화', hint: '광대 이야기', aliases: [] },
  { word: '괴물', topic: 'culture', category: '그때 그 영화', hint: '한강에 괴물이 나타난다', aliases: [] },
  { word: '기생충', topic: 'culture', category: '그때 그 영화', hint: '아카데미 작품상을 받았다', aliases: [] },
  { word: '슬램덩크', topic: 'culture', category: '그때 그 만화', hint: '왼손은 거들 뿐', aliases: [] },
  { word: '아기공룡둘리', topic: 'culture', category: '그때 그 만화', hint: '빙하를 타고 왔다', aliases: ['둘리'] },
  { word: '드래곤볼', topic: 'culture', category: '그때 그 만화', hint: '구슬을 모으면 소원이 이뤄진다', aliases: [] },
  { word: '세일러문', topic: 'culture', category: '그때 그 만화', hint: '달을 대신해 벌한다', aliases: [] },
  { word: '머털도사', topic: 'culture', category: '그때 그 만화', hint: '머리카락을 뽑아 도술을 부렸다', aliases: [] },
  { word: '영심이', topic: 'culture', category: '그때 그 만화', hint: '사춘기 소녀 이야기', aliases: [] },
  { word: '달려라하니', topic: 'culture', category: '그때 그 만화', hint: '육상 선수 소녀', aliases: [] },
  { word: '검정고무신', topic: 'culture', category: '그때 그 만화', hint: '형제 이야기', aliases: [] },
  { word: '날아라슈퍼보드', topic: 'culture', category: '그때 그 만화', hint: '손오공이 나온다', aliases: [] },
  { word: '꺼벙이', topic: 'culture', category: '그때 그 만화', hint: '명랑 만화의 주인공', aliases: [] },
  { word: '열혈강호', topic: 'culture', category: '그때 그 만화', hint: '무협 만화다', aliases: [] },
  { word: '레드문', topic: 'culture', category: '그때 그 만화', hint: '순정 판타지 만화', aliases: [] },
  { word: '마법천자문', topic: 'culture', category: '그때 그 만화', hint: '한자를 배우는 학습 만화', aliases: [] },
  { word: '만화한국사', topic: 'culture', category: '그때 그 만화', hint: '학습 만화 시리즈', aliases: [] },
  { word: '하이텔', topic: 'it', category: 'PC통신', hint: '전화선으로 접속했다', aliases: [] },
  { word: '천리안', topic: 'it', category: 'PC통신', hint: '3대 PC통신 중 하나', aliases: [] },
  { word: '나우누리', topic: 'it', category: 'PC통신', hint: '동호회가 활발했다', aliases: [] },
  { word: '유니텔', topic: 'it', category: 'PC통신', hint: '후발 PC통신 서비스', aliases: [] },
  { word: '모뎀', topic: 'it', category: 'PC통신', hint: '접속할 때 소리가 요란했다', aliases: [] },
  { word: '전화접속', topic: 'it', category: 'PC통신', hint: '쓰면 집 전화가 안 됐다', aliases: [] },
  { word: '아이러브스쿨', topic: 'it', category: 'PC통신', hint: '동창을 찾아줬다', aliases: [] },
  { word: '다모임', topic: 'it', category: 'PC통신', hint: '학교별로 모였다', aliases: [] },
  { word: '프리챌', topic: 'it', category: 'PC통신', hint: '커뮤니티 서비스였다', aliases: [] },
  { word: '텔넷', topic: 'it', category: 'PC통신', hint: '문자 기반으로 접속했다', aliases: [] },
  { word: '스타크래프트', topic: 'it', category: '그때 그 게임', hint: '저글링 러시', aliases: ['스타'] },
  { word: '바람의나라', topic: 'it', category: '그때 그 게임', hint: '국내 최초 그래픽 머드', aliases: [] },
  { word: '크레이지아케이드', topic: 'it', category: '그때 그 게임', hint: '물풍선을 터뜨렸다', aliases: ['크아'] },
  { word: '테트리스', topic: 'it', category: '그때 그 게임', hint: '한 줄씩 지웠다', aliases: [] },
  { word: '리니지', topic: 'it', category: '그때 그 게임', hint: '혈맹과 공성전', aliases: [] },
  { word: '디아블로', topic: 'it', category: '그때 그 게임', hint: '어두운 던전을 돌았다', aliases: [] },
  { word: '포트리스', topic: 'it', category: '그때 그 게임', hint: '각도와 세기를 맞췄다', aliases: [] },
  { word: '카트라이더', topic: 'it', category: '그때 그 게임', hint: '부스터를 썼다', aliases: [] },
  { word: '메이플스토리', topic: 'it', category: '그때 그 게임', hint: '옆으로 걷는 게임', aliases: [] },
  { word: '던전앤파이터', topic: 'it', category: '그때 그 게임', hint: '때리는 맛이 있었다', aliases: ['던파'] },
  { word: '서든어택', topic: 'it', category: '그때 그 게임', hint: '총으로 싸웠다', aliases: [] },
  { word: '오디션', topic: 'it', category: '그때 그 게임', hint: '박자에 맞춰 눌렀다', aliases: [] },
  { word: '워크래프트', topic: 'it', category: '그때 그 게임', hint: '유즈맵이 유행했다', aliases: [] },
  { word: '창세기전', topic: 'it', category: '그때 그 게임', hint: '국산 전략 시뮬레이션', aliases: [] },
  { word: '페르시아왕자', topic: 'it', category: '그때 그 게임', hint: '시간 안에 탈출했다', aliases: [] },
  { word: '갤러그', topic: 'it', category: '그때 그 게임', hint: '우주선으로 쐈다', aliases: [] },
  { word: '보글보글', topic: 'it', category: '그때 그 게임', hint: '거품으로 잡았다', aliases: [] },
  { word: '스트리트파이터', topic: 'it', category: '그때 그 게임', hint: '승룡권을 썼다', aliases: [] },
  { word: '킹오브파이터즈', topic: 'it', category: '그때 그 게임', hint: '3대3으로 싸웠다', aliases: ['KOF'] },
  { word: '버블보블', topic: 'it', category: '그때 그 게임', hint: '공룡이 주인공이었다', aliases: [] },
  { word: '삼국지', topic: 'it', category: '그때 그 게임', hint: '제갈량이 나오는 전략 게임', aliases: [] },
  { word: '프린세스메이커', topic: 'it', category: '그때 그 게임', hint: '딸을 키우는 게임', aliases: [] },
  { word: '어스토니시아스토리', topic: 'it', category: '그때 그 게임', hint: '국산 롤플레잉 게임', aliases: [] },
  { word: '악튜러스', topic: 'it', category: '그때 그 게임', hint: '국산 롤플레잉 게임', aliases: [] },
  { word: '붉은보석', topic: 'it', category: '그때 그 게임', hint: '국산 온라인 게임', aliases: [] },
  { word: '미르의전설', topic: 'it', category: '그때 그 게임', hint: '중국에서도 인기였다', aliases: [] },
  { word: '싸이월드', topic: 'it', category: '인터넷 서비스', hint: '도토리로 배경음악을 샀다', aliases: ['싸이'] },
  { word: '미니홈피', topic: 'it', category: '인터넷 서비스', hint: '일촌만 볼 수 있었다', aliases: [] },
  { word: '엠에스엔', topic: 'it', category: '인터넷 서비스', hint: '메신저로 대화했다', aliases: ['MSN'] },
  { word: '버디버디', topic: 'it', category: '인터넷 서비스', hint: '10대들이 많이 썼다', aliases: [] },
  { word: '네이트온', topic: 'it', category: '인터넷 서비스', hint: '회사에서도 썼다', aliases: [] },
  { word: '도토리', topic: 'it', category: '인터넷 서비스', hint: '아이템을 사는 화폐였다', aliases: [] },
  { word: '디시인사이드', topic: 'it', category: '인터넷 서비스', hint: '갤러리로 나뉘어 있다', aliases: ['디시'] },
  { word: '네이버지식인', topic: 'it', category: '인터넷 서비스', hint: '묻고 답했다', aliases: ['지식인'] },
  { word: '다음카페', topic: 'it', category: '인터넷 서비스', hint: '주제별로 모였다', aliases: [] },
  { word: '블로그', topic: 'it', category: '인터넷 서비스', hint: '글을 올리는 개인 공간', aliases: [] },
  { word: '트위터', topic: 'it', category: '인터넷 서비스', hint: '짧은 글을 올렸다', aliases: [] },
  { word: '카카오톡', topic: 'it', category: '인터넷 서비스', hint: '2010년에 나왔다', aliases: ['카톡'] },
  { word: '윈도구팔', topic: 'it', category: '그때 그 컴퓨터', hint: '시작 버튼이 생긴 운영체제', aliases: ['윈도95', '윈도우95'] },
  { word: '도스', topic: 'it', category: '그때 그 컴퓨터', hint: '까만 화면에 명령어를 쳤다', aliases: ['DOS'] },
  { word: '아래아한글', topic: 'it', category: '그때 그 컴퓨터', hint: '국산 문서 프로그램', aliases: ['한글97', '한컴오피스'] },
  { word: '시디롬', topic: 'it', category: '그때 그 컴퓨터', hint: '원반을 넣어 읽었다', aliases: ['CD롬'] },
  { word: '사운드카드', topic: 'it', category: '그때 그 컴퓨터', hint: '소리를 내려면 꽂아야 했다', aliases: [] },
  { word: '삼팔육', topic: 'it', category: '그때 그 컴퓨터', hint: '80386 프로세서를 줄여 불렀다', aliases: ['386'] },
  { word: '펜티엄', topic: 'it', category: '그때 그 컴퓨터', hint: '인텔의 프로세서 이름', aliases: [] },
  { word: '브이지에이', topic: 'it', category: '그때 그 컴퓨터', hint: '화면 규격 이름이었다', aliases: ['VGA'] },
  { word: '그래픽카드', topic: 'it', category: '그때 그 컴퓨터', hint: '화면을 그려주는 부품', aliases: [] },
  { word: '메인보드', topic: 'it', category: '그때 그 컴퓨터', hint: '부품을 꽂는 기판', aliases: [] },
  { word: '시피유', topic: 'it', category: '그때 그 컴퓨터', hint: '컴퓨터의 두뇌라 불린다', aliases: ['CPU'] },
  { word: '램', topic: 'it', category: '그때 그 컴퓨터', hint: '전원이 꺼지면 지워진다', aliases: ['RAM'] },
  { word: '아이엠에프', topic: 'economy', category: '경제 사건', hint: '1997년 구제금융', aliases: ['IMF'] },
  { word: '금모으기운동', topic: 'economy', category: '경제 사건', hint: '집에 있던 금을 내놨다', aliases: ['금모으기'] },
  { word: '외환위기', topic: 'economy', category: '경제 사건', hint: '환율이 급등했다', aliases: [] },
  { word: '벤처붐', topic: 'economy', category: '경제 사건', hint: '2000년 전후 창업 열풍', aliases: [] },
  { word: '닷컴버블', topic: 'economy', category: '경제 사건', hint: '인터넷 기업 주가가 급등락했다', aliases: [] },
  { word: '리먼사태', topic: 'economy', category: '경제 사건', hint: '2008년 금융위기의 계기', aliases: ['리먼브라더스'] },
  { word: '구조조정', topic: 'economy', category: '경제 사건', hint: '기업이 인력을 줄였다', aliases: [] },
  { word: '명예퇴직', topic: 'economy', category: '경제 사건', hint: '정년 전에 회사를 떠났다', aliases: [] },
  { word: '부도', topic: 'economy', category: '경제 사건', hint: '어음을 막지 못하는 상태', aliases: [] },
  { word: '흑자도산', topic: 'economy', category: '경제 사건', hint: '이익이 나도 현금이 없어 무너진다', aliases: [] },
  { word: '금융실명제', topic: 'economy', category: '경제 사건', hint: '1993년 실제 이름으로만 거래하게 했다', aliases: [] },
  { word: '경제협력개발기구', topic: 'economy', category: '경제 사건', hint: '1996년에 가입했다', aliases: ['OECD'] },
  { word: '주택청약', topic: 'economy', category: '경제 용어', hint: '통장을 만들어 순위를 쌓는다', aliases: ['청약'] },
  { word: '코스닥', topic: 'economy', category: '경제 용어', hint: '벤처 기업이 주로 상장했다', aliases: [] },
  { word: '코스피', topic: 'economy', category: '경제 용어', hint: '국내 대표 주가지수', aliases: [] },
  { word: '환율', topic: 'economy', category: '경제 용어', hint: '다른 나라 돈과 바꾸는 비율', aliases: [] },
  { word: '물가', topic: 'economy', category: '경제 용어', hint: '상품과 서비스의 값', aliases: [] },
  { word: '최저임금', topic: 'economy', category: '경제 용어', hint: '법으로 정한 시간당 하한', aliases: [] },
  { word: '소득공제', topic: 'economy', category: '경제 용어', hint: '세금을 계산할 때 빼주는 것', aliases: [] },
  { word: '예금자보호', topic: 'economy', category: '경제 용어', hint: '은행이 망해도 일정액을 돌려준다', aliases: [] },
  { word: '부가가치세', topic: 'economy', category: '경제 용어', hint: '물건값에 붙는 세금', aliases: ['부가세'] },
  { word: '적금', topic: 'economy', category: '경제 용어', hint: '매달 넣어 만기에 받는다', aliases: [] },
  { word: '대출이자', topic: 'economy', category: '경제 용어', hint: '빌린 돈에 붙는 값', aliases: [] },
  { word: '인플레이션', topic: 'economy', category: '경제 용어', hint: '물가가 지속적으로 오른다', aliases: [] },
  { word: '디플레이션', topic: 'economy', category: '경제 용어', hint: '물가가 지속적으로 내린다', aliases: [] },
  { word: '기준금리', topic: 'economy', category: '경제 용어', hint: '중앙은행이 정하는 금리', aliases: [] },
  { word: '국내총생산', topic: 'economy', category: '경제 용어', hint: '한 해 만들어낸 부가가치의 합', aliases: ['GDP'] },
  { word: '무역수지', topic: 'economy', category: '경제 용어', hint: '수출에서 수입을 뺀 것', aliases: [] },
  { word: '지방자치제', topic: 'society', category: '제도', hint: '1995년 단체장 선거가 부활했다', aliases: ['지방자치'] },
  { word: '주오일제', topic: 'society', category: '제도', hint: '토요일에 쉬게 됐다', aliases: ['주5일제'] },
  { word: '국민학교', topic: 'society', category: '제도', hint: '1996년에 이름이 바뀌었다', aliases: [] },
  { word: '수학능력시험', topic: 'society', category: '제도', hint: '1994년에 처음 치렀다', aliases: ['수능'] },
  { word: '의무교육', topic: 'society', category: '제도', hint: '일정 기간 학교에 다녀야 한다', aliases: [] },
  { word: '국민연금', topic: 'society', category: '제도', hint: '노후에 받는 연금 제도', aliases: [] },
  { word: '건강보험', topic: 'society', category: '제도', hint: '병원비를 나눠 부담한다', aliases: [] },
  { word: '주민등록증', topic: 'society', category: '제도', hint: '성인이 되면 발급받는다', aliases: [] },
  { word: '호주제', topic: 'society', category: '제도', hint: '2008년에 폐지됐다', aliases: [] },
  { word: '국민참여재판', topic: 'society', category: '제도', hint: '배심원이 참여한다', aliases: [] },
  { word: '실명제', topic: 'society', category: '제도', hint: '실제 이름을 쓰게 하는 제도', aliases: [] },
  { word: '선거권', topic: 'society', category: '제도', hint: '투표할 수 있는 권리', aliases: [] },
  { word: '성수대교', topic: 'society', category: '그때 그 사건', hint: '1994년에 무너졌다', aliases: [] },
  { word: '삼풍백화점', topic: 'society', category: '그때 그 사건', hint: '1995년에 붕괴했다', aliases: ['삼풍'] },
  { word: '대구지하철참사', topic: 'society', category: '그때 그 사건', hint: '2003년에 있었다', aliases: [] },
  { word: '태안기름유출', topic: 'society', category: '그때 그 사건', hint: '2007년 서해가 오염됐다', aliases: [] },
  { word: '숭례문화재', topic: 'society', category: '그때 그 사건', hint: '2008년 국보가 불탔다', aliases: ['숭례문'] },
  { word: '서울올림픽', topic: 'society', category: '그때 그 사건', hint: '1988년에 열렸다', aliases: [] },
  { word: '한일월드컵', topic: 'society', category: '그때 그 사건', hint: '2002년 공동 개최', aliases: [] },
  { word: '대전엑스포', topic: 'society', category: '그때 그 사건', hint: '1993년에 열렸다', aliases: ['엑스포'] },
  { word: '훈민정음', topic: 'history', category: '조선', hint: '세종이 반포했다', aliases: [] },
  { word: '거북선', topic: 'history', category: '조선', hint: '이순신이 이끌었다', aliases: [] },
  { word: '경국대전', topic: 'history', category: '조선', hint: '조선의 기본 법전', aliases: [] },
  { word: '집현전', topic: 'history', category: '조선', hint: '세종이 학자를 모은 기관', aliases: [] },
  { word: '임진왜란', topic: 'history', category: '조선', hint: '1592년에 시작됐다', aliases: [] },
  { word: '병자호란', topic: 'history', category: '조선', hint: '남한산성으로 피란했다', aliases: [] },
  { word: '대동법', topic: 'history', category: '조선', hint: '공납을 쌀로 통일했다', aliases: [] },
  { word: '탕평책', topic: 'history', category: '조선', hint: '붕당의 균형을 꾀했다', aliases: [] },
  { word: '규장각', topic: 'history', category: '조선', hint: '정조가 세운 왕실 도서관', aliases: [] },
  { word: '수원화성', topic: 'history', category: '조선', hint: '정조가 쌓은 성', aliases: [] },
  { word: '실학', topic: 'history', category: '조선', hint: '현실 문제를 다룬 학문', aliases: [] },
  { word: '한산도대첩', topic: 'history', category: '조선', hint: '학익진으로 이겼다', aliases: [] },
  { word: '명량대첩', topic: 'history', category: '조선', hint: '열두 척으로 싸웠다', aliases: [] },
  { word: '사육신', topic: 'history', category: '조선', hint: '단종 복위를 꾀했다', aliases: [] },
  { word: '훈구파', topic: 'history', category: '조선', hint: '조선 전기의 집권 세력', aliases: [] },
  { word: '사림파', topic: 'history', category: '조선', hint: '지방 사족 출신 세력', aliases: [] },
  { word: '조선왕조실록', topic: 'history', category: '조선', hint: '왕의 기록을 남긴 책', aliases: [] },
  { word: '동의보감', topic: 'history', category: '조선', hint: '허준이 편찬했다', aliases: [] },
  { word: '동학농민운동', topic: 'history', category: '근대', hint: '1894년 전봉준이 이끌었다', aliases: ['동학운동'] },
  { word: '삼일운동', topic: 'history', category: '근대', hint: '1919년 독립 만세', aliases: ['3·1운동'] },
  { word: '광복절', topic: 'history', category: '근대', hint: '8월 15일', aliases: [] },
  { word: '강화도조약', topic: 'history', category: '근대', hint: '1876년 개항의 계기', aliases: [] },
  { word: '갑오개혁', topic: 'history', category: '근대', hint: '신분제를 폐지했다', aliases: [] },
  { word: '을사늑약', topic: 'history', category: '근대', hint: '1905년 외교권을 빼앗겼다', aliases: [] },
  { word: '대한민국임시정부', topic: 'history', category: '근대', hint: '상하이에서 세워졌다', aliases: ['임시정부'] },
  { word: '청산리대첩', topic: 'history', category: '근대', hint: '김좌진이 이끌었다', aliases: [] },
  { word: '봉오동전투', topic: 'history', category: '근대', hint: '홍범도가 이끌었다', aliases: [] },
  { word: '안중근', topic: 'history', category: '근대', hint: '하얼빈에서 이토를 저격했다', aliases: [] },
  { word: '유관순', topic: 'history', category: '근대', hint: '아우내 장터에서 만세를 불렀다', aliases: [] },
  { word: '윤봉길', topic: 'history', category: '근대', hint: '상하이 훙커우 공원 의거', aliases: [] },
  { word: '독립문', topic: 'history', category: '근대', hint: '자주 독립을 상징한다', aliases: [] },
  { word: '갑신정변', topic: 'history', category: '근대', hint: '1884년 3일 만에 끝났다', aliases: [] },
  { word: '아관파천', topic: 'history', category: '근대', hint: '고종이 러시아 공사관으로 옮겼다', aliases: [] },
  { word: '새마을운동', topic: 'history', category: '현대', hint: '1970년대 농촌 근대화', aliases: [] },
  { word: '한국전쟁', topic: 'history', category: '현대', hint: '1950년에 일어났다', aliases: ['육이오', '6·25'] },
  { word: '휴전협정', topic: 'history', category: '현대', hint: '1953년에 맺어졌다', aliases: [] },
  { word: '사일구혁명', topic: 'history', category: '현대', hint: '1960년 학생이 일어섰다', aliases: ['4·19', '사일구'] },
  { word: '오일팔민주화운동', topic: 'history', category: '현대', hint: '1980년 광주에서 있었다', aliases: ['5·18', '오일팔'] },
  { word: '유월민주항쟁', topic: 'history', category: '현대', hint: '1987년 직선제를 이끌어냈다', aliases: ['6월항쟁', '유월항쟁'] },
  { word: '경부고속도로', topic: 'history', category: '현대', hint: '1970년에 개통했다', aliases: [] },
  { word: '포항제철', topic: 'history', category: '현대', hint: '산업화의 상징이었다', aliases: [] },
  { word: '남북정상회담', topic: 'history', category: '현대', hint: '2000년에 처음 열렸다', aliases: [] },
  { word: '이산가족찾기', topic: 'history', category: '현대', hint: '1983년 생방송으로 진행됐다', aliases: [] },
  { word: '르네상스', topic: 'world', category: '유럽사', hint: '고전의 부활', aliases: [] },
  { word: '산업혁명', topic: 'world', category: '유럽사', hint: '증기기관에서 시작됐다', aliases: [] },
  { word: '프랑스혁명', topic: 'world', category: '유럽사', hint: '바스티유 감옥 습격', aliases: [] },
  { word: '종교개혁', topic: 'world', category: '유럽사', hint: '루터가 95개조를 붙였다', aliases: [] },
  { word: '나폴레옹', topic: 'world', category: '유럽사', hint: '워털루에서 패배했다', aliases: [] },
  { word: '로마제국', topic: 'world', category: '유럽사', hint: '모든 길이 이곳으로 통했다', aliases: [] },
  { word: '십자군', topic: 'world', category: '유럽사', hint: '성지 회복을 내세웠다', aliases: [] },
  { word: '마그나카르타', topic: 'world', category: '유럽사', hint: '왕의 권한을 제한했다', aliases: [] },
  { word: '베르사유조약', topic: 'world', category: '유럽사', hint: '1차대전을 마무리했다', aliases: [] },
  { word: '계몽사상', topic: 'world', category: '유럽사', hint: '이성을 앞세웠다', aliases: [] },
  { word: '대항해시대', topic: 'world', category: '유럽사', hint: '새로운 항로를 찾아 나섰다', aliases: [] },
  { word: '백년전쟁', topic: 'world', category: '유럽사', hint: '영국과 프랑스가 오래 싸웠다', aliases: [] },
  { word: '흑사병', topic: 'world', category: '유럽사', hint: '중세 유럽 인구를 크게 줄였다', aliases: [] },
  { word: '절대왕정', topic: 'world', category: '유럽사', hint: '왕에게 권력이 집중됐다', aliases: [] },
  { word: '베를린장벽', topic: 'world', category: '세계 현대사', hint: '1989년에 무너졌다', aliases: [] },
  { word: '아폴로십일호', topic: 'world', category: '세계 현대사', hint: '1969년 달에 착륙했다', aliases: ['아폴로11호'] },
  { word: '제일차세계대전', topic: 'world', category: '세계 현대사', hint: '1914년에 시작됐다', aliases: ['1차대전', '제1차세계대전'] },
  { word: '제이차세계대전', topic: 'world', category: '세계 현대사', hint: '1939년에 시작됐다', aliases: ['2차대전', '제2차세계대전'] },
  { word: '냉전', topic: 'world', category: '세계 현대사', hint: '미국과 소련이 대립했다', aliases: [] },
  { word: '소련해체', topic: 'world', category: '세계 현대사', hint: '1991년에 무너졌다', aliases: [] },
  { word: '구일일테러', topic: 'world', category: '세계 현대사', hint: '2001년 뉴욕에서 일어났다', aliases: ['9·11', '911테러'] },
  { word: '국제연합', topic: 'world', category: '세계 현대사', hint: '1945년에 창설됐다', aliases: ['UN', '유엔'] },
  { word: '마셜플랜', topic: 'world', category: '세계 현대사', hint: '전후 유럽을 재건했다', aliases: [] },
  { word: '쿠바미사일위기', topic: 'world', category: '세계 현대사', hint: '1962년 핵전쟁 직전까지 갔다', aliases: [] },
  { word: '베트남전쟁', topic: 'world', category: '세계 현대사', hint: '미국이 오래 개입했다', aliases: [] },
  { word: '독일통일', topic: 'world', category: '세계 현대사', hint: '1990년에 이뤄졌다', aliases: [] },
  { word: '아파르트헤이트', topic: 'world', category: '세계 현대사', hint: '남아프리카의 인종 분리 정책', aliases: [] },
  { word: '콜럼버스', topic: 'world', category: '세계사 인물', hint: '1492년 항해', aliases: [] },
  { word: '간디', topic: 'world', category: '세계사 인물', hint: '비폭력 저항을 이끌었다', aliases: [] },
  { word: '아인슈타인', topic: 'world', category: '세계사 인물', hint: '상대성이론을 세웠다', aliases: [] },
  { word: '뉴턴', topic: 'world', category: '세계사 인물', hint: '만유인력을 정리했다', aliases: [] },
  { word: '다윈', topic: 'world', category: '세계사 인물', hint: '종의 기원을 썼다', aliases: [] },
  { word: '링컨', topic: 'world', category: '세계사 인물', hint: '노예 해방을 선언했다', aliases: [] },
  { word: '처칠', topic: 'world', category: '세계사 인물', hint: '2차대전 영국을 이끌었다', aliases: [] },
  { word: '마르코폴로', topic: 'world', category: '세계사 인물', hint: '동방견문록을 남겼다', aliases: [] },
  { word: '셰익스피어', topic: 'world', category: '세계사 인물', hint: '햄릿을 썼다', aliases: [] },
  { word: '베토벤', topic: 'world', category: '세계사 인물', hint: '운명 교향곡을 썼다', aliases: [] },
  { word: '갈릴레이', topic: 'world', category: '세계사 인물', hint: '지동설을 지지했다', aliases: [] },
  { word: '만델라', topic: 'world', category: '세계사 인물', hint: '남아프리카 대통령이 됐다', aliases: [] },
  { word: '마르틴루터', topic: 'world', category: '세계사 인물', hint: '종교개혁을 이끌었다', aliases: [] },
  { word: '칭기즈칸', topic: 'world', category: '세계사 인물', hint: '대제국을 세웠다', aliases: [] },
  { word: '차범근', topic: 'football', category: '축구 인물', hint: '독일 분데스리가에서 뛰었다', aliases: [] },
  { word: '박지성', topic: 'football', category: '축구 인물', hint: '맨체스터에서 뛰었다', aliases: [] },
  { word: '손흥민', topic: 'football', category: '축구 인물', hint: '프리미어리그 득점왕', aliases: [] },
  { word: '히딩크', topic: 'football', category: '축구 인물', hint: '2002년 대표팀 감독', aliases: [] },
  { word: '홍명보', topic: 'football', category: '축구 인물', hint: '2002년 주장이었다', aliases: [] },
  { word: '안정환', topic: 'football', category: '축구 인물', hint: '반지 세리머니로 유명하다', aliases: [] },
  { word: '이영표', topic: 'football', category: '축구 인물', hint: '왼쪽 측면 수비수였다', aliases: [] },
  { word: '김민재', topic: 'football', category: '축구 인물', hint: '수비수로 유럽에서 뛴다', aliases: [] },
  { word: '이강인', topic: 'football', category: '축구 인물', hint: '왼발이 좋은 미드필더', aliases: [] },
  { word: '황희찬', topic: 'football', category: '축구 인물', hint: '유럽에서 뛰는 공격수', aliases: [] },
  { word: '펠레', topic: 'football', category: '축구 인물', hint: '축구 황제로 불렸다', aliases: [] },
  { word: '마라도나', topic: 'football', category: '축구 인물', hint: '신의 손으로 알려졌다', aliases: [] },
  { word: '메시', topic: 'football', category: '축구 인물', hint: '아르헨티나 대표팀 주장', aliases: [] },
  { word: '호날두', topic: 'football', category: '축구 인물', hint: '포르투갈 대표팀 공격수', aliases: [] },
  { word: '베컴', topic: 'football', category: '축구 인물', hint: '프리킥이 유명했다', aliases: [] },
  { word: '지단', topic: 'football', category: '축구 인물', hint: '머리로 받은 결승이 유명하다', aliases: [] },
  { word: '오프사이드', topic: 'football', category: '축구 용어', hint: '앞서 있으면 반칙이다', aliases: [] },
  { word: '페널티킥', topic: 'football', category: '축구 용어', hint: '12야드에서 찬다', aliases: [] },
  { word: '프리킥', topic: 'football', category: '축구 용어', hint: '벽을 세우고 찬다', aliases: [] },
  { word: '코너킥', topic: 'football', category: '축구 용어', hint: '구석에서 올린다', aliases: [] },
  { word: '해트트릭', topic: 'football', category: '축구 용어', hint: '한 경기 세 골', aliases: [] },
  { word: '클린시트', topic: 'football', category: '축구 용어', hint: '한 골도 안 먹었다', aliases: [] },
  { word: '골키퍼', topic: 'football', category: '축구 용어', hint: '손을 쓸 수 있는 유일한 자리', aliases: [] },
  { word: '스트라이커', topic: 'football', category: '축구 용어', hint: '최전방 공격수', aliases: [] },
  { word: '미드필더', topic: 'football', category: '축구 용어', hint: '중원을 맡는다', aliases: [] },
  { word: '센터백', topic: 'football', category: '축구 용어', hint: '중앙 수비수', aliases: [] },
  { word: '레드카드', topic: 'football', category: '축구 용어', hint: '바로 퇴장이다', aliases: [] },
  { word: '옐로카드', topic: 'football', category: '축구 용어', hint: '두 장이면 퇴장', aliases: [] },
  { word: '연장전', topic: 'football', category: '축구 용어', hint: '정규 시간에 못 끝냈다', aliases: [] },
  { word: '승부차기', topic: 'football', category: '축구 용어', hint: '마지막 수단이다', aliases: [] },
  { word: '추가시간', topic: 'football', category: '축구 용어', hint: '주심이 더 준다', aliases: [] },
  { word: '백패스', topic: 'football', category: '축구 용어', hint: '뒤로 돌리는 패스', aliases: [] },
  { word: '월드컵', topic: 'football', category: '축구 대회·팀', hint: '4년마다 열린다', aliases: [] },
  { word: '한일월드컵', topic: 'football', category: '축구 대회·팀', hint: '2002년 공동 개최', aliases: [] },
  { word: '케이리그', topic: 'football', category: '축구 대회·팀', hint: '국내 프로 축구 리그', aliases: ['K리그'] },
  { word: '프리미어리그', topic: 'football', category: '축구 대회·팀', hint: '잉글랜드 최상위 리그', aliases: [] },
  { word: '분데스리가', topic: 'football', category: '축구 대회·팀', hint: '독일 최상위 리그', aliases: [] },
  { word: '라리가', topic: 'football', category: '축구 대회·팀', hint: '스페인 최상위 리그', aliases: [] },
  { word: '세리에아', topic: 'football', category: '축구 대회·팀', hint: '이탈리아 최상위 리그', aliases: [] },
  { word: '챔피언스리그', topic: 'football', category: '축구 대회·팀', hint: '유럽 클럽 최강전', aliases: [] },
  { word: '붉은악마', topic: 'football', category: '축구 대회·팀', hint: '대표팀 응원단', aliases: [] },
  { word: '오필승코리아', topic: 'football', category: '축구 대회·팀', hint: '2002년 거리 응원가', aliases: [] },
  { word: '아시안컵', topic: 'football', category: '축구 대회·팀', hint: '아시아 축구 대회', aliases: [] },
  { word: '국가대표', topic: 'football', category: '축구 대회·팀', hint: '태극마크를 단다', aliases: [] },
  { word: '박찬호', topic: 'baseball', category: '야구 인물', hint: '한국인 최초 메이저리거', aliases: [] },
  { word: '선동열', topic: 'baseball', category: '야구 인물', hint: '무등산 폭격기로 불렸다', aliases: [] },
  { word: '이승엽', topic: 'baseball', category: '야구 인물', hint: '한 시즌 56홈런을 쳤다', aliases: [] },
  { word: '류현진', topic: 'baseball', category: '야구 인물', hint: '메이저리그에서 던졌다', aliases: [] },
  { word: '김병현', topic: 'baseball', category: '야구 인물', hint: '메이저리그 마무리로 뛰었다', aliases: [] },
  { word: '추신수', topic: 'baseball', category: '야구 인물', hint: '메이저리그 외야수였다', aliases: [] },
  { word: '오승환', topic: 'baseball', category: '야구 인물', hint: '끝판대장으로 불렸다', aliases: [] },
  { word: '양준혁', topic: 'baseball', category: '야구 인물', hint: '타격 기계로 불렸다', aliases: [] },
  { word: '이대호', topic: 'baseball', category: '야구 인물', hint: '일본에서도 뛰었다', aliases: [] },
  { word: '최동원', topic: 'baseball', category: '야구 인물', hint: '부산의 전설로 남았다', aliases: [] },
  { word: '장효조', topic: 'baseball', category: '야구 인물', hint: '타격의 달인으로 불렸다', aliases: [] },
  { word: '김성근', topic: 'baseball', category: '야구 인물', hint: '야신으로 불린 감독', aliases: [] },
  { word: '만루홈런', topic: 'baseball', category: '야구 용어', hint: '한 방에 4점', aliases: [] },
  { word: '완봉승', topic: 'baseball', category: '야구 용어', hint: '한 점도 안 주고 이겼다', aliases: [] },
  { word: '노히트노런', topic: 'baseball', category: '야구 용어', hint: '안타를 하나도 안 맞았다', aliases: [] },
  { word: '퍼펙트게임', topic: 'baseball', category: '야구 용어', hint: '한 명도 못 나갔다', aliases: [] },
  { word: '사이클링히트', topic: 'baseball', category: '야구 용어', hint: '한 경기에 안타를 종류별로', aliases: [] },
  { word: '병살타', topic: 'baseball', category: '야구 용어', hint: '한 번에 둘이 죽었다', aliases: [] },
  { word: '희생번트', topic: 'baseball', category: '야구 용어', hint: '자기가 죽고 주자를 보낸다', aliases: [] },
  { word: '도루', topic: 'baseball', category: '야구 용어', hint: '다음 베이스를 훔친다', aliases: [] },
  { word: '삼진', topic: 'baseball', category: '야구 용어', hint: '스트라이크 셋', aliases: [] },
  { word: '볼넷', topic: 'baseball', category: '야구 용어', hint: '볼 넷이면 걸어 나간다', aliases: [] },
  { word: '세이브', topic: 'baseball', category: '야구 용어', hint: '리드를 지키고 끝냈다', aliases: [] },
  { word: '타율', topic: 'baseball', category: '야구 용어', hint: '안타를 타수로 나눈다', aliases: [] },
  { word: '방어율', topic: 'baseball', category: '야구 용어', hint: '9이닝당 자책점', aliases: ['평균자책점'] },
  { word: '출루율', topic: 'baseball', category: '야구 용어', hint: '살아 나간 비율', aliases: [] },
  { word: '구원투수', topic: 'baseball', category: '야구 용어', hint: '선발 다음에 나온다', aliases: [] },
  { word: '마무리투수', topic: 'baseball', category: '야구 용어', hint: '마지막을 맡는다', aliases: [] },
  { word: '대타', topic: 'baseball', category: '야구 용어', hint: '대신 타석에 선다', aliases: [] },
  { word: '직구', topic: 'baseball', category: '야구 용어', hint: '가장 빠른 공', aliases: [] },
  { word: '변화구', topic: 'baseball', category: '야구 용어', hint: '휘어져 들어가는 공', aliases: [] },
  { word: '슬라이더', topic: 'baseball', category: '야구 용어', hint: '옆으로 휘는 변화구', aliases: [] },
  { word: '해태타이거즈', topic: 'baseball', category: '야구 팀·대회', hint: '90년대 최다 우승 팀', aliases: ['해태'] },
  { word: '엘지트윈스', topic: 'baseball', category: '야구 팀·대회', hint: '잠실을 쓴다', aliases: ['LG트윈스'] },
  { word: '롯데자이언츠', topic: 'baseball', category: '야구 팀·대회', hint: '부산 연고 구단', aliases: ['롯데'] },
  { word: '삼성라이온즈', topic: 'baseball', category: '야구 팀·대회', hint: '대구 연고 구단', aliases: ['삼성'] },
  { word: '두산베어스', topic: 'baseball', category: '야구 팀·대회', hint: '잠실을 함께 쓴다', aliases: ['두산'] },
  { word: '기아타이거즈', topic: 'baseball', category: '야구 팀·대회', hint: '광주 연고 구단', aliases: ['기아'] },
  { word: '한화이글스', topic: 'baseball', category: '야구 팀·대회', hint: '대전 연고 구단', aliases: ['한화'] },
  { word: '한국시리즈', topic: 'baseball', category: '야구 팀·대회', hint: '프로야구 최종 결승', aliases: [] },
  { word: '케이비오', topic: 'baseball', category: '야구 팀·대회', hint: '국내 프로야구 리그', aliases: ['KBO'] },
  { word: '메이저리그', topic: 'baseball', category: '야구 팀·대회', hint: '미국 프로야구', aliases: ['MLB'] },
  { word: '월드시리즈', topic: 'baseball', category: '야구 팀·대회', hint: '메이저리그 최종 결승', aliases: [] },
  { word: '가을야구', topic: 'baseball', category: '야구 팀·대회', hint: '포스트시즌을 부르는 말', aliases: [] },
  { word: '허재', topic: 'basketball', category: '농구 인물', hint: '농구 대통령으로 불렸다', aliases: [] },
  { word: '서장훈', topic: 'basketball', category: '농구 인물', hint: '키 큰 국내 센터였다', aliases: [] },
  { word: '이상민', topic: 'basketball', category: '농구 인물', hint: '국내 프로 가드로 유명하다', aliases: [] },
  { word: '문경은', topic: 'basketball', category: '농구 인물', hint: '3점슛이 좋았다', aliases: [] },
  { word: '현주엽', topic: 'basketball', category: '농구 인물', hint: '국내 프로에서 뛰었다', aliases: [] },
  { word: '하승진', topic: 'basketball', category: '농구 인물', hint: '국내 최장신 선수였다', aliases: [] },
  { word: '마이클조던', topic: 'basketball', category: '농구 인물', hint: '시카고에서 뛰었다', aliases: ['조던'] },
  { word: '코비브라이언트', topic: 'basketball', category: '농구 인물', hint: 'LA 레이커스 전설', aliases: ['코비'] },
  { word: '르브론제임스', topic: 'basketball', category: '농구 인물', hint: '현대 NBA 대표 선수', aliases: ['르브론'] },
  { word: '샤킬오닐', topic: 'basketball', category: '농구 인물', hint: '거대한 센터였다', aliases: [] },
  { word: '스테판커리', topic: 'basketball', category: '농구 인물', hint: '3점슛으로 유명하다', aliases: ['커리'] },
  { word: '야오밍', topic: 'basketball', category: '농구 인물', hint: '중국 출신 센터였다', aliases: [] },
  { word: '덩크슛', topic: 'basketball', category: '농구 용어', hint: '림에 내리꽂는다', aliases: ['덩크'] },
  { word: '레이업', topic: 'basketball', category: '농구 용어', hint: '골밑에 살짝 올린다', aliases: [] },
  { word: '삼점슛', topic: 'basketball', category: '농구 용어', hint: '아크 밖에서 넣는다', aliases: ['3점슛'] },
  { word: '자유투', topic: 'basketball', category: '농구 용어', hint: '반칙을 받아 혼자 던진다', aliases: [] },
  { word: '리바운드', topic: 'basketball', category: '농구 용어', hint: '튀어나온 공을 잡는다', aliases: [] },
  { word: '어시스트', topic: 'basketball', category: '농구 용어', hint: '득점을 도왔다', aliases: [] },
  { word: '스틸', topic: 'basketball', category: '농구 용어', hint: '공을 가로챘다', aliases: [] },
  { word: '블록슛', topic: 'basketball', category: '농구 용어', hint: '슛을 쳐냈다', aliases: [] },
  { word: '트래블링', topic: 'basketball', category: '농구 용어', hint: '공을 들고 걸었다', aliases: [] },
  { word: '더블드리블', topic: 'basketball', category: '농구 용어', hint: '드리블을 두 번 했다', aliases: [] },
  { word: '속공', topic: 'basketball', category: '농구 용어', hint: '빠르게 몰아친다', aliases: ['패스트브레이크'] },
  { word: '지역방어', topic: 'basketball', category: '농구 용어', hint: '구역을 나눠 막는다', aliases: ['존디펜스'] },
  { word: '픽앤롤', topic: 'basketball', category: '농구 용어', hint: '막아주고 돌아 들어간다', aliases: [] },
  { word: '버저비터', topic: 'basketball', category: '농구 용어', hint: '종료 부저와 함께 들어갔다', aliases: [] },
  { word: '트리플더블', topic: 'basketball', category: '농구 용어', hint: '세 부문에서 두 자리', aliases: [] },
  { word: '센터', topic: 'basketball', category: '농구 용어', hint: '골밑을 지킨다', aliases: [] },
  { word: '포인트가드', topic: 'basketball', category: '농구 용어', hint: '공을 운반한다', aliases: [] },
  { word: '식스맨', topic: 'basketball', category: '농구 용어', hint: '벤치에서 나오는 주력', aliases: [] },
  { word: '케이비엘', topic: 'basketball', category: '농구 리그·문화', hint: '국내 프로 농구 리그', aliases: ['KBL'] },
  { word: '엔비에이', topic: 'basketball', category: '농구 리그·문화', hint: '미국 프로 농구', aliases: ['NBA'] },
  { word: '슬램덩크', topic: 'basketball', category: '농구 리그·문화', hint: '북산고가 나오는 농구 만화', aliases: [] },
  { word: '마지막승부', topic: 'basketball', category: '농구 리그·문화', hint: '농구 소재 드라마였다', aliases: [] },
  { word: '농구대잔치', topic: 'basketball', category: '농구 리그·문화', hint: '90년대 초 인기 대회', aliases: [] },
  { word: '대학농구', topic: 'basketball', category: '농구 리그·문화', hint: '연고전이 뜨거웠다', aliases: [] },
  { word: '올스타전', topic: 'basketball', category: '농구 리그·문화', hint: '인기 선수들이 모인다', aliases: [] },
  { word: '플레이오프', topic: 'basketball', category: '농구 리그·문화', hint: '정규 시즌 다음 단계', aliases: [] },
  { word: '김연아', topic: 'sports', category: '스포츠 인물', hint: '피겨 금메달을 땄다', aliases: [] },
  { word: '박세리', topic: 'sports', category: '스포츠 인물', hint: '맨발 투혼', aliases: [] },
  { word: '황영조', topic: 'sports', category: '스포츠 인물', hint: '바르셀로나 마라톤 금메달', aliases: [] },
  { word: '진종오', topic: 'sports', category: '스포츠 인물', hint: '사격 금메달리스트', aliases: [] },
  { word: '양학선', topic: 'sports', category: '스포츠 인물', hint: '체조 금메달리스트', aliases: [] },
  { word: '장미란', topic: 'sports', category: '스포츠 인물', hint: '역도 금메달리스트', aliases: [] },
  { word: '이봉주', topic: 'sports', category: '스포츠 인물', hint: '마라톤 국가대표였다', aliases: [] },
  { word: '김제덕', topic: 'sports', category: '스포츠 인물', hint: '양궁 금메달리스트', aliases: [] },
  { word: '안산', topic: 'sports', category: '스포츠 인물', hint: '양궁 3관왕이었다', aliases: [] },
  { word: '우사인볼트', topic: 'sports', category: '스포츠 인물', hint: '단거리 세계기록 보유자', aliases: [] },
  { word: '마이클펠프스', topic: 'sports', category: '스포츠 인물', hint: '수영 다관왕이었다', aliases: [] },
  { word: '나달', topic: 'sports', category: '스포츠 인물', hint: '흙코트에 강했다', aliases: [] },
  { word: '올림픽', topic: 'sports', category: '대회·종목', hint: '4년마다 열린다', aliases: [] },
  { word: '아시안게임', topic: 'sports', category: '대회·종목', hint: '아시아 종합 대회', aliases: [] },
  { word: '전국체전', topic: 'sports', category: '대회·종목', hint: '국내 종합 체육대회', aliases: [] },
  { word: '평창동계올림픽', topic: 'sports', category: '대회·종목', hint: '2018년 강원도에서 열렸다', aliases: ['평창올림픽'] },
  { word: '시드니올림픽', topic: 'sports', category: '대회·종목', hint: '2000년에 열렸다', aliases: [] },
  { word: '베이징올림픽', topic: 'sports', category: '대회·종목', hint: '2008년에 열렸다', aliases: [] },
  { word: '런던올림픽', topic: 'sports', category: '대회·종목', hint: '2012년에 열렸다', aliases: [] },
  { word: '양궁', topic: 'sports', category: '대회·종목', hint: '활을 쏜다', aliases: [] },
  { word: '태권도', topic: 'sports', category: '대회·종목', hint: '우리나라에서 시작됐다', aliases: [] },
  { word: '쇼트트랙', topic: 'sports', category: '대회·종목', hint: '좁은 링크를 돈다', aliases: [] },
  { word: '스피드스케이팅', topic: 'sports', category: '대회·종목', hint: '넓은 링크를 돈다', aliases: [] },
  { word: '피겨스케이팅', topic: 'sports', category: '대회·종목', hint: '점프와 회전으로 겨룬다', aliases: [] },
  { word: '배드민턴', topic: 'sports', category: '대회·종목', hint: '셔틀콕을 친다', aliases: [] },
  { word: '탁구', topic: 'sports', category: '대회·종목', hint: '작은 공을 친다', aliases: [] },
  { word: '마라톤', topic: 'sports', category: '대회·종목', hint: '42.195km 를 뛴다', aliases: [] },
  { word: '역도', topic: 'sports', category: '대회·종목', hint: '바벨을 들어 올린다', aliases: [] },
]
