import type { TopicId } from '@retro/types'
import type { NonEmptyArray } from '@retro/room-kit'

/**
 * 단어 연상 소재 — 02 문서 §3.9
 *
 * 초성 퀴즈와 단어 풀을 공유하되, **설명 가능한 단어만** 남긴다.
 * 콘텐츠 비용이 거의 0인 게임이다 — 설명은 사람이 만든다.
 *
 * `script` 는 혼자 모드 전용이다 (03 문서 §7.3 · 04 문서 §5.5.2).
 * 사람 출제자가 있으면 쓰이지 않는다. 화면에 가짜 출제자를 세우지 않고,
 * 설명이 문제의 일부로 표시된다.
 */

export interface AssocWord {
  readonly word: string
  readonly topic: TopicId
  readonly category: string
  /** 사전에 등록된 다른 정답 */
  readonly aliases: readonly string[]
  /** 출제자가 쓸 수 없는 말. 코드가 자동 확장한다 (02 문서 §3.4) */
  readonly banned: readonly string[]
  /** 혼자 모드에서 시간에 따라 흘릴 설명 3단계 */
  readonly script: readonly [string, string, string]
}

export const SAMPLE_WORDS: NonEmptyArray<AssocWord> = [
  {
    word: '삐삐',
    topic: 'daily',
    category: '90년대 물건',
    aliases: ['무선호출기', '페이저'],
    banned: ['beeper', 'pager'],
    script: [
      '허리에 차고 다니던 물건이에요',
      '숫자로 메시지를 보냈어요',
      '8282 같은 숫자 암호가 있었죠',
    ],
  },
  {
    word: '워크맨',
    topic: 'daily',
    category: '90년대 물건',
    aliases: [],
    banned: ['walkman'],
    script: [
      '주머니에 넣고 다녔어요',
      '테이프를 넣고 이어폰을 꽂았죠',
      '늘어지면 연필로 감았어요',
    ],
  },
  {
    word: '다마고치',
    topic: 'daily',
    category: '90년대 물건',
    aliases: [],
    banned: ['tamagotchi'],
    script: [
      '손바닥만 한 계란 모양이었어요',
      '밥을 안 주면 죽었어요',
      '수업 시간에 몰래 눌렀죠',
    ],
  },
  {
    word: '브로마이드',
    topic: 'daily',
    category: '90년대 물건',
    aliases: [],
    banned: [],
    script: [
      '벽에 붙이는 물건이에요',
      '좋아하는 가수가 크게 인쇄돼 있었죠',
      '잡지 부록으로 자주 들어 있었어요',
    ],
  },
  {
    word: '공중전화',
    topic: 'daily',
    category: '90년대 물건',
    aliases: [],
    banned: [],
    script: [
      '길거리에 부스가 있었어요',
      '카드나 동전을 넣고 썼죠',
      '뒤에 줄이 길면 눈치가 보였어요',
    ],
  },
  {
    word: '책받침',
    topic: 'daily',
    category: '90년대 물건',
    aliases: [],
    banned: [],
    script: [
      '공책 밑에 깔았어요',
      '연예인 사진이 인쇄돼 있었죠',
      '문방구에서 팔았어요',
    ],
  },
  {
    word: '연탄',
    topic: 'daily',
    category: '90년대 물건',
    aliases: [],
    banned: [],
    script: [
      '까맣고 구멍이 뚫려 있어요',
      '겨울에 아궁이에 넣었죠',
      '갈아 끼울 때 집게를 썼어요',
    ],
  },
  {
    word: '버스토큰',
    topic: 'daily',
    category: '90년대 물건',
    aliases: [],
    banned: [],
    script: [
      '동전처럼 생겼어요',
      '버스 탈 때 통에 넣었죠',
      '문방구에서도 팔았어요',
    ],
  },
  {
    word: '필름카메라',
    topic: 'daily',
    category: '90년대 물건',
    aliases: [],
    banned: [],
    script: [
      '찍고 바로 못 봐요',
      '현상소에 맡겨야 했죠',
      '한 통에 24장이나 36장이었어요',
    ],
  },
  {
    word: '보온도시락',
    topic: 'daily',
    category: '90년대 물건',
    aliases: [],
    banned: [],
    script: [
      '겨울에 유용했어요',
      '점심시간까지 따뜻했죠',
      '가방에서 국물이 새기도 했어요',
    ],
  },
  {
    word: '오락실',
    topic: 'daily',
    category: '그때 그 장소',
    aliases: ['게임장'],
    banned: [],
    script: [
      '동전을 잔뜩 바꿔서 갔어요',
      '기계 위에 동전을 쌓아두고 줄을 섰죠',
      '학교 끝나고 가면 혼났어요',
    ],
  },
  {
    word: '롤라장',
    topic: 'daily',
    category: '그때 그 장소',
    aliases: ['롤러장'],
    banned: [],
    script: [
      '바퀴 달린 신발을 빌려 신었어요',
      '가운데서 넘어지면 창피했죠',
      '음악이 크게 나오던 실내 공간이에요',
    ],
  },
  {
    word: '만화방',
    topic: 'daily',
    category: '그때 그 장소',
    aliases: ['만화가게'],
    banned: [],
    script: [
      '앉아서 몇 시간이고 있었어요',
      '라면도 팔았죠',
      '한 권씩 쌓아놓고 봤어요',
    ],
  },
  {
    word: '비디오가게',
    topic: 'daily',
    category: '그때 그 장소',
    aliases: ['비디오대여점'],
    banned: [],
    script: [
      '주말 저녁에 온 가족이 갔어요',
      '테이프를 빌려서 봤죠',
      '늦게 반납하면 연체료를 냈어요',
    ],
  },
  {
    word: '문방구',
    topic: 'daily',
    category: '그때 그 장소',
    aliases: [],
    banned: [],
    script: [
      '학교 앞에 꼭 하나 있었어요',
      '준비물을 여기서 샀죠',
      '앞에 오락기가 놓여 있기도 했어요',
    ],
  },
  {
    word: '목욕탕',
    topic: 'daily',
    category: '그때 그 장소',
    aliases: ['공중목욕탕'],
    banned: [],
    script: [
      '수건과 비누를 챙겨 갔어요',
      '탕에 오래 앉아 있었죠',
      '때를 밀어주는 분이 계셨어요',
    ],
  },
  {
    word: '독서실',
    topic: 'daily',
    category: '그때 그 장소',
    aliases: [],
    banned: [],
    script: [
      '조용히 해야 했어요',
      '칸막이 책상에 앉았죠',
      '월 단위로 자리를 빌렸어요',
    ],
  },
  {
    word: '피시방',
    topic: 'daily',
    category: '그때 그 장소',
    aliases: ['PC방'],
    banned: [],
    script: [
      '시간을 사서 썼어요',
      '옆자리 소리가 다 들렸죠',
      '라면도 팔았어요',
    ],
  },
  {
    word: '쌍쌍바',
    topic: 'daily',
    category: '그때 그 군것질',
    aliases: [],
    banned: [],
    script: [
      '여름에 먹던 거예요',
      '둘이 나눠 먹으라고 만든 모양이었죠',
      '반으로 쪼갤 때 한쪽이 꼭 작게 갈라졌어요',
    ],
  },
  {
    word: '달고나',
    topic: 'daily',
    category: '그때 그 군것질',
    aliases: ['뽑기'],
    banned: [],
    script: [
      '길에서 만들어 줬어요',
      '국자에 설탕을 녹였죠',
      '모양을 잘 떼면 하나 더 받았어요',
    ],
  },
  {
    word: '죠스바',
    topic: 'daily',
    category: '그때 그 군것질',
    aliases: [],
    banned: [],
    script: [
      '파란색 아이스크림이에요',
      '먹으면 혀가 물들었죠',
      '상어 이름이 붙어 있어요',
    ],
  },
  {
    word: '건빵',
    topic: 'daily',
    category: '그때 그 군것질',
    aliases: [],
    banned: [],
    script: [
      '딱딱한 과자예요',
      '군대에서도 나왔죠',
      '별 모양 사탕이 같이 들어 있었어요',
    ],
  },
  {
    word: '번데기',
    topic: 'daily',
    category: '그때 그 군것질',
    aliases: [],
    banned: [],
    script: [
      '길에서 종이컵에 담아 팔았어요',
      '냄새가 멀리서도 났죠',
      '이쑤시개로 찍어 먹었어요',
    ],
  },
  {
    word: '노래방',
    topic: 'culture',
    category: '문화·연예',
    aliases: [],
    banned: [],
    script: [
      '방을 빌려서 놀아요',
      '화면에 가사가 나오죠',
      '탬버린을 흔들었어요',
    ],
  },
  {
    word: '브이에이치에스',
    topic: 'culture',
    category: '문화·연예',
    aliases: ['비디오테이프', 'VHS'],
    banned: [],
    script: [
      '네모난 플라스틱 통이에요',
      '되감아서 반납해야 했죠',
      '늘어지면 화면이 지직거렸어요',
    ],
  },
  {
    word: '슬램덩크',
    topic: 'culture',
    category: '문화·연예',
    aliases: [],
    banned: [],
    script: [
      '농구 만화예요',
      '북산고가 나오죠',
      '왼손은 거들 뿐이라는 대사가 유명해요',
    ],
  },
  {
    word: '세일러문',
    topic: 'culture',
    category: '문화·연예',
    aliases: [],
    banned: [],
    script: [
      '변신하는 소녀 만화예요',
      '달을 대신해 벌한다고 했죠',
      '친구들이 행성 이름을 하나씩 맡았어요',
    ],
  },
  {
    word: '가요톱텐',
    topic: 'culture',
    category: '문화·연예',
    aliases: [],
    banned: [],
    script: [
      '음악 순위 프로그램이에요',
      '1위를 하면 트로피를 줬죠',
      '5주 연속이면 명예의 전당에 올랐어요',
    ],
  },
  {
    word: '브로마이드사진',
    topic: 'culture',
    category: '문화·연예',
    aliases: [],
    banned: [],
    script: [
      '큰 사진이에요',
      '잡지 부록으로 나왔죠',
      '방 벽에 붙였어요',
    ],
  },
  {
    word: '모뎀',
    topic: 'it',
    category: 'IT·기술',
    aliases: [],
    banned: [],
    script: [
      '인터넷에 연결할 때 썼어요',
      '연결할 때 요란한 소리가 났죠',
      '쓰는 동안 집 전화가 안 됐어요',
    ],
  },
  {
    word: '플로피디스켓',
    topic: 'it',
    category: 'IT·기술',
    aliases: ['디스켓'],
    banned: [],
    script: [
      '네모난 저장 장치예요',
      '지금도 저장 아이콘으로 남아 있죠',
      '용량이 아주 작았어요',
    ],
  },
  {
    word: '싸이월드',
    topic: 'it',
    category: 'IT·기술',
    aliases: ['싸이'],
    banned: [],
    script: [
      '개인 공간을 꾸미는 서비스였어요',
      '친구 관계를 일촌이라고 불렀죠',
      '배경음악을 사려면 도토리가 필요했어요',
    ],
  },
  {
    word: '스타크래프트',
    topic: 'it',
    category: 'IT·기술',
    aliases: ['스타'],
    banned: [],
    script: [
      '실시간 전략 게임이에요',
      '종족이 셋이죠',
      'PC방을 가득 채웠어요',
    ],
  },
  {
    word: '테트리스',
    topic: 'it',
    category: 'IT·기술',
    aliases: [],
    banned: [],
    script: [
      '블록이 위에서 내려와요',
      '빈틈없이 채우면 한 줄이 사라지죠',
      '길쭉한 조각을 기다리게 돼요',
    ],
  },
  {
    word: '카트라이더',
    topic: 'it',
    category: 'IT·기술',
    aliases: [],
    banned: [],
    script: [
      '레이싱 게임이에요',
      '아이템을 쓰며 달렸죠',
      '부스터를 모아 썼어요',
    ],
  },
  {
    word: '메신저',
    topic: 'it',
    category: 'IT·기술',
    aliases: [],
    banned: [],
    script: [
      '실시간으로 대화하는 프로그램이에요',
      '접속 상태가 보였죠',
      '대화창이 깜빡였어요',
    ],
  },
  {
    word: '환율',
    topic: 'economy',
    category: '경제',
    aliases: [],
    banned: [],
    script: [
      '나라 사이의 돈 값이에요',
      '오르면 수입품이 비싸지죠',
      '외환위기 때 크게 올랐어요',
    ],
  },
  {
    word: '적금',
    topic: 'economy',
    category: '경제',
    aliases: [],
    banned: [],
    script: [
      '은행 상품이에요',
      '매달 일정 금액을 넣죠',
      '만기에 이자를 더해 받아요',
    ],
  },
  {
    word: '물가',
    topic: 'economy',
    category: '경제',
    aliases: [],
    banned: [],
    script: [
      '전반적인 값을 말해요',
      '오르면 살림이 팍팍해지죠',
      '통계청이 지수로 발표해요',
    ],
  },
  {
    word: '부도',
    topic: 'economy',
    category: '경제',
    aliases: [],
    banned: [],
    script: [
      '기업에게 최악의 상황이에요',
      '돈을 제때 못 갚는 거죠',
      '어음을 막지 못하면 벌어져요',
    ],
  },
  {
    word: '청약',
    topic: 'economy',
    category: '경제',
    aliases: ['주택청약'],
    banned: [],
    script: [
      '집을 사려는 사람이 준비해요',
      '통장을 오래 유지할수록 유리하죠',
      '순위라는 게 있어요',
    ],
  },
  {
    word: '수능',
    topic: 'society',
    category: '정치·사회',
    aliases: ['수학능력시험'],
    banned: [],
    script: [
      '해마다 11월에 있어요',
      '전국이 조용해지죠',
      '듣기 평가 때는 비행기도 안 떠요',
    ],
  },
  {
    word: '주민등록증',
    topic: 'society',
    category: '정치·사회',
    aliases: [],
    banned: [],
    script: [
      '만 17세가 되면 만들어요',
      '지갑에 넣고 다니죠',
      '번호 앞자리가 생일이에요',
    ],
  },
  {
    word: '국민연금',
    topic: 'society',
    category: '정치·사회',
    aliases: [],
    banned: [],
    script: [
      '나중에 받으려고 지금 내요',
      '월급에서 빠져나가죠',
      '노후 소득을 위한 제도예요',
    ],
  },
  {
    word: '투표',
    topic: 'society',
    category: '정치·사회',
    aliases: [],
    banned: [],
    script: [
      '도장을 찍어요',
      '신분증을 가져가야 하죠',
      '손등에 표시를 해줬어요',
    ],
  },
  {
    word: '거북선',
    topic: 'history',
    category: '한국사',
    aliases: [],
    banned: [],
    script: [
      '조선 시대 배예요',
      '지붕에 쇠못을 박았다고 하죠',
      '이순신 장군이 썼어요',
    ],
  },
  {
    word: '훈민정음',
    topic: 'history',
    category: '한국사',
    aliases: [],
    banned: [],
    script: [
      '글자에 대한 책이에요',
      '백성을 가르치는 바른 소리라는 뜻이죠',
      '세종대왕이 만들었어요',
    ],
  },
  {
    word: '수원화성',
    topic: 'history',
    category: '한국사',
    aliases: [],
    banned: [],
    script: [
      '조선 후기에 쌓은 성이에요',
      '정약용이 거중기를 썼죠',
      '정조가 세웠어요',
    ],
  },
  {
    word: '삼일운동',
    topic: 'history',
    category: '한국사',
    aliases: ['3·1운동'],
    banned: [],
    script: [
      '1919년에 일어났어요',
      '전국에서 만세를 불렀죠',
      '탑골공원에서 시작됐어요',
    ],
  },
  {
    word: '경부고속도로',
    topic: 'history',
    category: '한국사',
    aliases: [],
    banned: [],
    script: [
      '1970년에 완공됐어요',
      '서울과 부산을 이었죠',
      '산업화의 상징으로 꼽혀요',
    ],
  },
  {
    word: '베를린장벽',
    topic: 'world',
    category: '세계사',
    aliases: [],
    banned: [],
    script: [
      '도시를 둘로 나눴어요',
      '넘으려다 목숨을 잃은 사람도 있었죠',
      '1989년에 무너졌어요',
    ],
  },
  {
    word: '피라미드',
    topic: 'world',
    category: '세계사',
    aliases: [],
    banned: [],
    script: [
      '아주 오래된 건축물이에요',
      '삼각형 모양이죠',
      '이집트에 있어요',
    ],
  },
  {
    word: '만리장성',
    topic: 'world',
    category: '세계사',
    aliases: [],
    banned: [],
    script: [
      '아주 긴 성벽이에요',
      '북쪽을 막으려고 쌓았죠',
      '중국에 있어요',
    ],
  },
  {
    word: '콜로세움',
    topic: 'world',
    category: '세계사',
    aliases: [],
    banned: [],
    script: [
      '고대 경기장이에요',
      '검투사가 싸웠죠',
      '로마에 있어요',
    ],
  },
  {
    word: '산업혁명',
    topic: 'world',
    category: '세계사',
    aliases: [],
    banned: [],
    script: [
      '18세기에 시작됐어요',
      '증기기관이 핵심이었죠',
      '공장이 생기고 도시가 커졌어요',
    ],
  },
  {
    word: '월드컵',
    topic: 'sports',
    category: '스포츠',
    aliases: [],
    banned: [],
    script: [
      '4년마다 열려요',
      '32개국이 겨뤘죠',
      '2002년에 우리나라에서도 열렸어요',
    ],
  },
  {
    word: '붉은악마',
    topic: 'sports',
    category: '스포츠',
    aliases: [],
    banned: [],
    script: [
      '응원단 이름이에요',
      '빨간 옷을 맞춰 입었죠',
      '거리 응원을 이끌었어요',
    ],
  },
  {
    word: '마라톤',
    topic: 'sports',
    category: '스포츠',
    aliases: [],
    banned: [],
    script: [
      '아주 오래 달려요',
      '42.195km 를 뛰죠',
      '황영조 선수가 금메달을 땄어요',
    ],
  },
  {
    word: '한국시리즈',
    topic: 'sports',
    category: '스포츠',
    aliases: [],
    banned: [],
    script: [
      '가을에 열려요',
      '프로야구 최종 승부죠',
      '7전 4선승제예요',
    ],
  },
  {
    word: '피겨스케이팅',
    topic: 'sports',
    category: '스포츠',
    aliases: [],
    banned: [],
    script: [
      '얼음 위에서 해요',
      '점프와 회전으로 점수를 매기죠',
      '김연아 선수가 유명해요',
    ],
  },
]
