import type { TopicId } from '@retro/types'
import type { NonEmptyArray } from '@retro/room-kit'

/**
 * 스케치 소재.
 *
 * **그릴 수 있어야 한다.** 이게 다른 게임과 결정적으로 다른 조건이다.
 * 「외환위기」는 초성 퀴즈에서는 좋은 문제지만 그림으로는 성립하지 않는다.
 * 그래서 이 목록은 눈에 보이는 것 — 물건 · 동물 · 탈것 · 장소 — 으로 채운다.
 *
 * 인용이 없다. 작품 제목이나 대사를 소재로 쓰지 않는다.
 */

export interface SketchSubject {
  readonly word: string
  readonly topic: TopicId
  readonly category: string
  readonly aliases: readonly string[]
}

export const SAMPLE_SUBJECTS: NonEmptyArray<SketchSubject> = [
  { word: '삐삐', topic: 'daily', category: '그때 그 물건', aliases: ['무선호출기'] },
  { word: '공중전화', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '워크맨', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '다마고치', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '카세트테이프', topic: 'daily', category: '그때 그 물건', aliases: ['카세트'] },
  { word: '플로피디스켓', topic: 'daily', category: '그때 그 물건', aliases: ['디스켓'] },
  { word: '연탄', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '선풍기', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '책받침', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '색종이', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '샤프', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '딱지', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '구슬', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '제기', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '팽이', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '고무줄', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '실내화', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '도시락', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '보온병', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '우산', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '안경', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '시계', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '자전거', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '가방', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '모자', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '신발', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '양말', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '전화기', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '텔레비전', topic: 'daily', category: '그때 그 물건', aliases: ['TV'] },
  { word: '라디오', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '냉장고', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '세탁기', topic: 'daily', category: '그때 그 물건', aliases: [] },
  { word: '오락실', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '문방구', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '만화방', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '놀이터', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '학교', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '교실', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '운동장', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '목욕탕', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '시장', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '버스정류장', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '지하철역', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '편의점', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '빨래방', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '사진관', topic: 'daily', category: '그때 그 장소', aliases: [] },
  { word: '아이스크림', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '솜사탕', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '붕어빵', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '호빵', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '떡볶이', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '순대', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '김밥', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '라면', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '짜장면', topic: 'daily', category: '그때 그 군것질', aliases: ['자장면'] },
  { word: '치킨', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '피자', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '햄버거', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '도넛', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '사탕', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '초콜릿', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '과자', topic: 'daily', category: '그때 그 군것질', aliases: [] },
  { word: '강아지', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '고양이', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '토끼', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '거북이', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '코끼리', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '기린', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '사자', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '호랑이', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '원숭이', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '펭귄', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '돌고래', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '상어', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '나비', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '꿀벌', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '공룡', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '나무', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '장미', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '해바라기', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '무지개', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '눈사람', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '화산', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '바다', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '구름', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '번개', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '별똥별', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '초승달', topic: 'daily', category: '동물·자연', aliases: [] },
  { word: '마이크', topic: 'culture', category: '문화·연예', aliases: [] },
  { word: '기타', topic: 'culture', category: '문화·연예', aliases: [] },
  { word: '피아노', topic: 'culture', category: '문화·연예', aliases: [] },
  { word: '드럼', topic: 'culture', category: '문화·연예', aliases: [] },
  { word: '카메라', topic: 'culture', category: '문화·연예', aliases: [] },
  { word: '영화관', topic: 'culture', category: '문화·연예', aliases: [] },
  { word: '팝콘', topic: 'culture', category: '문화·연예', aliases: [] },
  { word: '무대', topic: 'culture', category: '문화·연예', aliases: [] },
  { word: '트로피', topic: 'culture', category: '문화·연예', aliases: [] },
  { word: '풍선', topic: 'culture', category: '문화·연예', aliases: [] },
  { word: '로봇', topic: 'anime-jp', category: '캐릭터·만화', aliases: [] },
  { word: '마법사', topic: 'anime-jp', category: '캐릭터·만화', aliases: [] },
  { word: '공룡알', topic: 'anime-jp', category: '캐릭터·만화', aliases: [] },
  { word: '유령', topic: 'anime-jp', category: '캐릭터·만화', aliases: [] },
  { word: '외계인', topic: 'anime-jp', category: '캐릭터·만화', aliases: [] },
  { word: '우주선', topic: 'anime-jp', category: '캐릭터·만화', aliases: [] },
  { word: '보물상자', topic: 'anime-jp', category: '캐릭터·만화', aliases: [] },
  { word: '마법지팡이', topic: 'anime-jp', category: '캐릭터·만화', aliases: [] },
  { word: '왕관', topic: 'anime-jp', category: '캐릭터·만화', aliases: [] },
  { word: '가면', topic: 'anime-jp', category: '캐릭터·만화', aliases: [] },
  { word: '조이스틱', topic: 'game', category: '게임', aliases: [] },
  { word: '게임기', topic: 'game', category: '게임', aliases: [] },
  { word: '동전', topic: 'game', category: '게임', aliases: [] },
  { word: '컨트롤러', topic: 'game', category: '게임', aliases: [] },
  { word: '키보드', topic: 'game', category: '게임', aliases: [] },
  { word: '마우스', topic: 'game', category: '게임', aliases: [] },
  { word: '컴퓨터', topic: 'game', category: '게임', aliases: [] },
  { word: '모니터', topic: 'game', category: '게임', aliases: [] },
  { word: '헤드폰', topic: 'game', category: '게임', aliases: [] },
  { word: '축구공', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '야구공', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '농구공', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '배트', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '글러브', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '골대', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '메달', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '운동화', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '자전거헬멧', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '줄넘기', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '셔틀콕', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '탁구채', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '스케이트', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '스키', topic: 'sports', category: '스포츠', aliases: [] },
  { word: '버스', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '택시', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '기차', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '비행기', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '돛단배', topic: 'society', category: '탈것·건물', aliases: ['배'] },
  { word: '소방차', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '구급차', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '경찰차', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '트럭', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '오토바이', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '아파트', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '학교건물', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '병원', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '우체국', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '등대', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '다리', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '신호등', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '우체통', topic: 'society', category: '탈것·건물', aliases: [] },
  { word: '거북선', topic: 'history', category: '역사', aliases: [] },
  { word: '한복', topic: 'history', category: '역사', aliases: [] },
  { word: '부채', topic: 'history', category: '역사', aliases: [] },
  { word: '장구', topic: 'history', category: '역사', aliases: [] },
  { word: '하회탈', topic: 'history', category: '역사', aliases: [] },
  { word: '기와집', topic: 'history', category: '역사', aliases: [] },
  { word: '초가집', topic: 'history', category: '역사', aliases: [] },
  { word: '성곽', topic: 'history', category: '역사', aliases: ['성'] },
  { word: '첨성대', topic: 'history', category: '역사', aliases: [] },
  { word: '석탑', topic: 'history', category: '역사', aliases: [] },
  { word: '피라미드', topic: 'world', category: '세계', aliases: [] },
  { word: '만리장성', topic: 'world', category: '세계', aliases: [] },
  { word: '에펠탑', topic: 'world', category: '세계', aliases: [] },
  { word: '풍차', topic: 'world', category: '세계', aliases: [] },
  { word: '지구본', topic: 'world', category: '세계', aliases: [] },
  { word: '나침반', topic: 'world', category: '세계', aliases: [] },
  { word: '지도', topic: 'world', category: '세계', aliases: [] },
  { word: '열기구', topic: 'world', category: '세계', aliases: [] },
  { word: '등대불', topic: 'world', category: '세계', aliases: [] },
]
